In [30]:
import csv
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [45]:
#Load Data

a = "~/Documents/GitHub/CampaignDonations/MoHs_VoteRatios_113_116_Film.csv" 
b = "~/Documents/GitHub/CampaignDonations/walt_disney_moh20122018.csv" 

df_Vote = pd.read_csv(a)
df_Disney = pd.read_csv(b)

df_Vote.head()

,person,name,party,VoteAlong113thRatio,VoteAlong114thRatio,VoteAlong115thRatio,VoteAlong116thRatio
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",Democrat,0.00,0.666667,NaN,NaN
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",Democrat,0.75,0.333333,0.6,1.0
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",Democrat,0.50,NaN,NaN,NaN
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",Democrat,0.00,0.333333,0.4,1.0

In [46]:
import re #Regular Expressions
#df_Vote["name"] = re.sub("Rep", "a", df_Vote["name"]iloc)

df_Vote["party_short"] = "N"

for x in range(len(df_Vote)):
    if (df_Vote["party"].iloc[x] == "Democrat"):
        df_Vote["party_short"].iloc[x] = "D"
    
    
for x in range(len(df_Vote)):
    if (df_Vote["party"].iloc[x] == "Republican"):
        df_Vote["party_short"].iloc[x] = "R"

In [86]:
df_Vote["Pure_name"] =  df_Vote["name"]

for x in range(len(df_Vote)):
    df_Vote["Pure_name"].iloc[x] = re.sub("Rep.", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("]", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("[0-9]", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("\[D, -", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("\[R, -", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("Jr.", "",  df_Vote["Pure_name"].iloc[x])
    
#Problem: By deleting the add-on "Jr." there might some MoH that end up having the same ID 

df_Vote["LastName"] = df_Vote["Pure_name"].str.split().str[-1]
df_Vote["FirstName"] = df_Vote["Pure_name"].str.split().str[0]

# Create an ID in the disney data to be able to merge with vote data 
df_Vote["ID_NameParty"] = df_Vote["FirstName"]+ df_Vote["LastName"] + df_Vote["party_short"]


df_Vote.head()

,person,name,party,VoteAlong113thRatio,VoteAlong114thRatio,VoteAlong115thRatio,VoteAlong116thRatio,party_short,Last_name,Suffix,LastName,ID_NameParty,Pure_name,FirstName
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,N,Robert “Rob” Andrews,Andrews,Andrews,RobertAndrewsN,Robert “Rob” Andrews,Robert
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",Democrat,0.00,0.666667,NaN,NaN,D,Xavier Becerra,Becerra,Becerra,XavierBecerraD,Xavier Becerra,Xavier
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",Democrat,0.75,0.333333,0.6,1.0,D,Sanford Bishop,Bishop,Bishop,SanfordBishopD,Sanford Bishop,Sanford
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",Democrat,0.50,NaN,NaN,NaN,D,Timothy Bishop,Bishop,Bishop,TimothyBishopD,Timothy Bishop,Timothy
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",Democrat,0.00,0.333333,0.4,1.0,D,Earl Blumenauer,Blumenauer,Blumenauer,EarlBlumenauerD,Earl Blumenauer,Earl

In [87]:
#len(df_Vote) #697
unique_MoHs = df_Vote["ID_NameParty"]
length_all = len(unique_MoHs)

unique_MoHs = unique_MoHs.drop_duplicates()

unique_MoHs = pd.DataFrame(unique_MoHs)

length_unique = len(unique_MoHs)

print(length_all , length_unique)

697 675

In [83]:

# Create an ID in the disney data to be able to merge with vote data 
df_Disney["ID_NameParty"] = df_Disney["first"] + df_Disney["last"] + df_Disney["party"]

df_Disney.head()

,first,last,party,donations2012,donations2014,donations2016,donations2018,pageid,wikidataid,wikititle,...,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116,ID_NameParty
0,Daniel,Webster,R,12000.0,11250.0,2000.0,1000.0,13719578.0,Q1163099,Daniel_Webster_(Florida_politician),...,1949-04-27,NaN,"38.34722,-81.63333",NaN,4.0,True,True,True,True,DanielWebsterR
1,Adam,Schiff,D,10500.0,7500.0,5000.0,40020.0,408932.0,Q350843,Adam_Schiff,...,1960-06-22,NaN,"42.27917,-71.41667",NaN,4.0,True,True,True,True,AdamSchiffD
2,Fred,Upton,R,6500.0,3500.0,1500.0,1500.0,468360.0,Q505236,Fred_Upton,...,1953-04-23,NaN,"42.09806,-86.48417",NaN,4.0,True,True,True,True,FredUptonR
3,Steny,Hoyer,D,4675.0,0.0,0.0,2000.0,414552.0,Q516515,Steny_Hoyer,...,1939-06-14,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True,StenyHoyerD
4,Greg,Walden,R,4000.0,3000.0,9000.0,10000.0,699507.0,Q1397359,Greg_Walden,...,1957-01-10,NaN,"45.60111,-121.18278",NaN,4.0,True,True,True,True,GregWaldenR

In [91]:
Disney_Donor_Vote= pd.merge(df_Vote ,df_Disney,on = "ID_NameParty", how='left')

Disney_Donor_Vote.head()


compression_opts = dict(method='zip',
                        archive_name='Disney_Donor_Vote.csv')  
Disney_Donor_Vote.to_csv('Disney_Donor_Vote.zip', index=False,
          compression=compression_opts)

     person                                      name  VoteAlong113thRatio  \
0    400008  Rep. Robert “Rob” Andrews [D, 1990-2014]                  NaN
1    400021        Rep. Xavier Becerra [D, 2013-2017]                 0.00
2    400030    Rep. Sanford Bishop Jr. [D, 1993-2022]                 0.75
3    400031        Rep. Timothy Bishop [D, 2003-2014]                 0.50
4    400033       Rep. Earl Blumenauer [D, 1996-2022]                 0.00
..      ...                                       ...                  ...
674  412837          Rep. Carol Miller [R, 2019-2022]                  NaN
675  407672          Rep. Kweisi Mfume [D, 2020-2022]                  NaN
676  412843           Rep. Fred Keller [R, 2019-2022]                  NaN
677  412844            Rep. Dan Bishop [R, 2019-2022]                  NaN
678  412845        Rep. Gregory Murphy [R, 2019-2022]                  NaN

     VoteAlong114thRatio  VoteAlong115thRatio  VoteAlong116thRatio
0                    NaN                  NaN                  NaN
1               0.666667                  NaN                  NaN
2               0.333333                  0.6                  1.0
3                    NaN                  NaN                  NaN
4               0.333333                  0.4                  1.0
..                   ...                  ...                  ...
674                  NaN                  NaN                  0.0
675                  NaN                  NaN                  NaN
676                  NaN                  NaN                  NaN
677                  NaN                  NaN                  NaN
678                  NaN                  NaN                  NaN

[679 rows x 6 columns]

,first,last,party,donations2012,donations2014,donations2016,donations2018,pageid,wikidataid,wikititle,...,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116,ID_NameParty
0,Daniel,Webster,R,12000.0,11250.0,2000.0,1000.0,13719578.0,Q1163099,Daniel_Webster_(Florida_politician),...,1949-04-27,NaN,"38.34722,-81.63333",NaN,4.0,True,True,True,True,WebsterR
1,Adam,Schiff,D,10500.0,7500.0,5000.0,40020.0,408932.0,Q350843,Adam_Schiff,...,1960-06-22,NaN,"42.27917,-71.41667",NaN,4.0,True,True,True,True,SchiffD
2,Fred,Upton,R,6500.0,3500.0,1500.0,1500.0,468360.0,Q505236,Fred_Upton,...,1953-04-23,NaN,"42.09806,-86.48417",NaN,4.0,True,True,True,True,UptonR
3,Steny,Hoyer,D,4675.0,0.0,0.0,2000.0,414552.0,Q516515,Steny_Hoyer,...,1939-06-14,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True,HoyerD
4,Greg,Walden,R,4000.0,3000.0,9000.0,10000.0,699507.0,Q1397359,Greg_Walden,...,1957-01-10,NaN,"45.60111,-121.18278",NaN,4.0,True,True,True,True,WaldenR