In [2]:
import csv
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [3]:
# Merging Voting Data from Different Categories 

# Load the data

a1 = "~/Documents/GitHub/CampaignDonations/Output_Data/02a_02f_Data_Output/MoHs_VoteRatios_113_116_FS_IIR.csv"
a2 = "~/Documents/GitHub/CampaignDonations/Output_Data/02a_02f_Data_Output/MoHs_VoteRatios_113_116_FS_FSS.csv"
a3 = "~/Documents/GitHub/CampaignDonations/Output_Data/02a_02f_Data_Output/MoHs_VoteRatios_113_116_FS_CM.csv"
a4 = "~/Documents/GitHub/CampaignDonations/Output_Data/02a_02f_Data_Output/MoHs_VoteRatios_113_116_FS_REB.csv"

df_Vote_FS_IIR = pd.read_csv(a1)
df_Vote_FS_FSS = pd.read_csv(a2)
df_Vote_FS_CM = pd.read_csv(a3)
df_Vote_FS_REB = pd.read_csv(a4)

df_Vote_FS_FSS = df_Vote_FS_FSS.drop(columns="person")
df_Vote_FS_CM = df_Vote_FS_CM.drop(columns="person")
df_Vote_FS_REB = df_Vote_FS_REB.drop(columns="person")

In [4]:
# Merge 

df_Vote = pd.merge(df_Vote_FS_IIR ,df_Vote_FS_FSS ,on = "name", how='left')
df_Vote = pd.merge(df_Vote  , df_Vote_FS_CM ,on = "name", how='left')
df_Vote = pd.merge(df_Vote  , df_Vote_FS_REB ,on = "name", how='left')

df_Vote.head()

,person,name,VoteAlong113thRatio_FS_IIR,VoteAlong114thRatio_FS_IIR,VoteAlong115thRatio_FS_IIR,VoteAlong116thRatio_FS_IIR,VoteAlong113thRatio_FS_FSS,VoteAlong114thRatio_FS_FSS,VoteAlong115thRatio_FS_FSS,VoteAlong116thRatio_FS_FSS,VoteAlong113thRatio_FS_CM,VoteAlong114thRatio_FS_CM,VoteAlong115thRatio_FS_CM,VoteAlong116thRatio_FS_CM,VoteAlong113thRatio_FS_REB,VoteAlong114thRatio_FS_REB,VoteAlong115thRatio_FS_REB,VoteAlong116thRatio_FS_REB
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",0.333333,0.6,NaN,NaN,0.333333,0.000000,NaN,NaN,0.571429,0.2,NaN,1.0,0.666667,0.00,NaN,NaN
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",0.500000,0.8,0.428571,1.0,0.666667,0.333333,0.555556,1.0,0.714286,0.8,0.25,1.0,0.666667,0.75,0.0,1.0
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",0.500000,NaN,NaN,NaN,0.666667,NaN,NaN,NaN,0.714286,NaN,NaN,1.0,0.666667,NaN,NaN,NaN
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",0.333333,0.8,0.428571,1.0,0.333333,0.333333,0.222222,1.0,0.571429,0.4,0.00,1.0,0.666667,0.50,0.0,1.0

,pageid,party,wikidataid,wikititle,name,sex,ethnicity,religion,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116
0,25016198,R,Q4954892,Bradley_Byrne,Bradley Byrne,male,white,NaN,1955-02-16,NaN,"30.72767,-88.05267",NaN,4,True,True,True,True
1,29218153,R,Q439117,Martha_Roby,Martha Roby,female,white,NaN,1976-07-26,NaN,"32.36167,-86.27917",NaN,4,True,True,True,True
2,407888,R,Q693238,Mike_Rogers_(Alabama_politician),Mike D. Rogers,male,white,protestantism baptist,1958-07-16,NaN,"41.6111,-87.4931",NaN,4,True,True,True,True
3,407889,R,Q672671,Robert_Aderholt,Robert Aderholt,male,white,protestantism methodist,1965-07-22,NaN,"34.23013,-87.61898",NaN,4,True,True,True,True
4,27586834,R,Q1941306,Mo_Brooks,Mo Brooks,male,white,NaN,1954-04-29,NaN,"32.77611,-79.9325",NaN,4,True,True,True,True

In [6]:
df_Vote["party_short"] = df_Vote["name"]

import re #Regular Expressions

for x in range(len(df_Vote)):
    df_Vote["party_short"].iloc[x] = re.sub(".+D,.+", "D",  df_Vote["party_short"].iloc[x])
    df_Vote["party_short"].iloc[x] = re.sub(".+R,.+", "R",  df_Vote["party_short"].iloc[x])
    
# Setting all non-republicans and democrats to Neutral "N"    
for x in range(len(df_Vote)):
    if (df_Vote["party_short"].iloc[x] != "D" and df_Vote["party_short"].iloc[x] != "R" ):
        df_Vote["party_short"].iloc[x] = "N"

In [7]:

df_Vote["Pure_name"] =  df_Vote["name"]

for x in range(len(df_Vote)):
    df_Vote["Pure_name"].iloc[x] = re.sub("Rep.", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("]", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("[0-9]", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("\[D, -", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("\[R, -", "",  df_Vote["Pure_name"].iloc[x])
    df_Vote["Pure_name"].iloc[x] = re.sub("Jr.", "",  df_Vote["Pure_name"].iloc[x])
    
#Problem: By deleting the add-on "Jr." there might some MoH that end up having the same ID 

df_Vote["LastName"] = df_Vote["Pure_name"].str.split().str[-1]
df_Vote["FirstName"] = df_Vote["Pure_name"].str.split().str[0]

# Create an ID to be able to merge with MOH DAta
df_Vote["ID_NameParty"] = df_Vote["FirstName"]+ df_Vote["LastName"] + df_Vote["party_short"]


df_Vote.head()

,person,name,VoteAlong113thRatio_FS_IIR,VoteAlong114thRatio_FS_IIR,VoteAlong115thRatio_FS_IIR,VoteAlong116thRatio_FS_IIR,VoteAlong113thRatio_FS_FSS,VoteAlong114thRatio_FS_FSS,VoteAlong115thRatio_FS_FSS,VoteAlong116thRatio_FS_FSS,...,VoteAlong116thRatio_FS_CM,VoteAlong113thRatio_FS_REB,VoteAlong114thRatio_FS_REB,VoteAlong115thRatio_FS_REB,VoteAlong116thRatio_FS_REB,party_short,Pure_name,LastName,FirstName,ID_NameParty
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,NaN,NaN,NaN,NaN,D,Robert “Rob” Andrews,Andrews,Robert,RobertAndrewsD
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",0.333333,0.6,NaN,NaN,0.333333,0.000000,NaN,NaN,...,1.0,0.666667,0.00,NaN,NaN,D,Xavier Becerra,Becerra,Xavier,XavierBecerraD
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",0.500000,0.8,0.428571,1.0,0.666667,0.333333,0.555556,1.0,...,1.0,0.666667,0.75,0.0,1.0,D,Sanford Bishop,Bishop,Sanford,SanfordBishopD
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",0.500000,NaN,NaN,NaN,0.666667,NaN,NaN,NaN,...,1.0,0.666667,NaN,NaN,NaN,D,Timothy Bishop,Bishop,Timothy,TimothyBishopD
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",0.333333,0.8,0.428571,1.0,0.333333,0.333333,0.222222,1.0,...,1.0,0.666667,0.50,0.0,1.0,D,Earl Blumenauer,Blumenauer,Earl,EarlBlumenauerD

In [8]:

#len(df_Vote) #697
unique_MoHs = df_Vote["ID_NameParty"]
length_all = len(unique_MoHs)

unique_MoHs = unique_MoHs.drop_duplicates()

unique_MoHs = pd.DataFrame(unique_MoHs)

length_unique = len(unique_MoHs)

print(length_all , length_unique)

685 663

In [9]:
#Load DataSet that contains all MoH and the Disney Donation Data

bb = "~/Documents/GitHub/CampaignDonations/Output_Data/walt_disney_moh20122018.csv"

df_MoH = pd.read_csv(bb)

df_MoH.head()

,first,last,party,donations2012,donations2014,donations2016,donations2018,pageid,wikidataid,wikititle,...,religion,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116
0,Daniel,Webster,R,12000.0,11250.0,2000.0,1000.0,13719578.0,Q1163099,Daniel_Webster_(Florida_politician),...,NaN,1949-04-27,NaN,"38.34722,-81.63333",NaN,4.0,True,True,True,True
1,Adam,Schiff,D,10500.0,7500.0,5000.0,40020.0,408932.0,Q350843,Adam_Schiff,...,judaism,1960-06-22,NaN,"42.27917,-71.41667",NaN,4.0,True,True,True,True
2,Fred,Upton,R,6500.0,3500.0,1500.0,1500.0,468360.0,Q505236,Fred_Upton,...,protestantism,1953-04-23,NaN,"42.09806,-86.48417",NaN,4.0,True,True,True,True
3,Steny,Hoyer,D,4675.0,0.0,0.0,2000.0,414552.0,Q516515,Steny_Hoyer,...,protestantism baptist,1939-06-14,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True
4,Greg,Walden,R,4000.0,3000.0,9000.0,10000.0,699507.0,Q1397359,Greg_Walden,...,anglicanism,1957-01-10,NaN,"45.60111,-121.18278",NaN,4.0,True,True,True,True

In [10]:
# Change df_MoH a little bit to make sure the already included donations data is properly marked as Dinsey 

df_MoH["disney_donations2012"] = df_MoH["donations2012"] 
df_MoH["disney_donations2014"] = df_MoH["donations2014"] 
df_MoH["disney_donations2016"] = df_MoH["donations2016"] 
df_MoH["disney_donations2018"] = df_MoH["donations2018"] 

list = ["donations2012", "donations2014" ,"donations2016" ,"donations2018"]
df_MoH = df_MoH.drop(columns = list)

In [11]:

# Create an ID in the MoH data to be able to merge with vote data 
df_MoH["ID_NameParty"] = df_MoH["first"] + df_MoH["last"] + df_MoH["party"]

df_MoH.head()

,first,last,party,pageid,wikidataid,wikititle,name,sex,ethnicity,religion,...,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116,disney_donations2012,disney_donations2014,disney_donations2016,disney_donations2018,ID_NameParty
0,Daniel,Webster,R,13719578.0,Q1163099,Daniel_Webster_(Florida_politician),Daniel Webster,male,white,NaN,...,4.0,True,True,True,True,12000.0,11250.0,2000.0,1000.0,DanielWebsterR
1,Adam,Schiff,D,408932.0,Q350843,Adam_Schiff,Adam Schiff,male,white,judaism,...,4.0,True,True,True,True,10500.0,7500.0,5000.0,40020.0,AdamSchiffD
2,Fred,Upton,R,468360.0,Q505236,Fred_Upton,Fred Upton,male,white,protestantism,...,4.0,True,True,True,True,6500.0,3500.0,1500.0,1500.0,FredUptonR
3,Steny,Hoyer,D,414552.0,Q516515,Steny_Hoyer,Steny H. Hoyer,male,white,protestantism baptist,...,4.0,True,True,True,True,4675.0,0.0,0.0,2000.0,StenyHoyerD
4,Greg,Walden,R,699507.0,Q1397359,Greg_Walden,Greg Walden,male,white,anglicanism,...,4.0,True,True,True,True,4000.0,3000.0,9000.0,10000.0,GregWaldenR

In [15]:
# Get Data From other Donors: Bloomberg and Citadel to merge it as well

a1 = "~/Documents/GitHub/CampaignDonations/Output_Data/Donation_MoH_Bloomberg_Citadel.csv"
df_BloomCitadel = pd.read_csv(a1)

# Create ID_NameParty Column for merging 
df_BloomCitadel["ID_NameParty"] = df_BloomCitadel["first"] + df_BloomCitadel["last"] + df_BloomCitadel["party"]

df_BloomCitadel.head()

,first,last,party,Citadel_donations2012,Citadel_donations2014,Citadel_donations2016,Citadel_donations2018,Bloomberg_donations2012,Bloomberg_donations2014,Bloomberg_donations2016,...,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116,ID_NameParty
0,Nita,Lowey,D,5000.0,2600.0,10800.0,18100.0,5000.0,2600.0,10800.0,...,1937-07-05,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True,NitaLoweyD
1,Hakeem,Jeffries,D,2000.0,0.0,0.0,0.0,2000.0,0.0,0.0,...,1970-08-04,NaN,"40.69278,-73.99028",NaN,4.0,True,True,True,True,HakeemJeffriesD
2,Sean,Maloney,D,750.0,2000.0,21600.0,16500.0,750.0,2000.0,21600.0,...,1966-07-30,NaN,"45.4,-71.9",NaN,4.0,True,True,True,True,SeanMaloneyD
3,Grace,Meng,D,500.0,0.0,0.0,0.0,500.0,0.0,0.0,...,1975-10-01,NaN,"40.70417,-73.91778",NaN,4.0,True,True,True,True,GraceMengD
4,David,Cicilline,D,500.0,0.0,0.0,0.0,500.0,0.0,0.0,...,1961-07-15,NaN,"41.83083,-71.415",NaN,4.0,True,True,True,True,DavidCicillineD

In [18]:
# Merge ALl datasets 

MoH_Vote_Data = pd.merge(df_Vote , df_MoH, on = "ID_NameParty", how='left')

MoH_Vote_Data = pd.merge(MoH_Vote_Data  , df_BloomCitadel, on = "ID_NameParty", how='left')

MoH_Vote_Data.head()

,person,name_x,VoteAlong113thRatio_FS_IIR,VoteAlong114thRatio_FS_IIR,VoteAlong115thRatio_FS_IIR,VoteAlong116thRatio_FS_IIR,VoteAlong113thRatio_FS_FSS,VoteAlong114thRatio_FS_FSS,VoteAlong115thRatio_FS_FSS,VoteAlong116thRatio_FS_FSS,...,religion_y,birth_y,death_y,birthplace_y,deathplace_y,Number_Sessions_Served_y,Session_113_y,Session_114_y,Session_115_y,Session_116_y
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",0.333333,0.6,NaN,NaN,0.333333,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",0.500000,0.8,0.428571,1.0,0.666667,0.333333,0.555556,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",0.500000,NaN,NaN,NaN,0.666667,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",0.333333,0.8,0.428571,1.0,0.333333,0.333333,0.222222,1.0,...,NaN,1948-08-16,NaN,"45.51667,-122.66667",NaN,4.0,True,True,True,True

In [19]:

# Merge with Vote Data in Category Film (from former disney trial)

# Get the data
a = "~/Documents/GitHub/CampaignDonations/Output_Data/MoHs_VoteRatios_113_116_Film.csv" 
df_FilmVote = pd.read_csv(a)


# Change df_FilmVote a little bit to make sure the already included vote data is properly marked 
df_FilmVote["VoteAlong113thRatio_Film"] = df_FilmVote["VoteAlong113thRatio"] 
df_FilmVote["VoteAlong114thRatio_Film"] = df_FilmVote["VoteAlong114thRatio"] 
df_FilmVote["VoteAlong115thRatio_Film"] = df_FilmVote["VoteAlong115thRatio"] 
df_FilmVote["VoteAlong116thRatio_Film"] = df_FilmVote["VoteAlong116thRatio"] 

list = ["VoteAlong113thRatio", "VoteAlong114thRatio", "VoteAlong115thRatio", "VoteAlong116thRatio"]
df_FilmVote = df_FilmVote.drop(columns = list)


# Merge on basis of "name"
#MoH_Vote_Data = MoH_Vote_Data.rename({'name_x':'name'}, axis=1) # Change x_name to name to be able to merge

# Merge on "name"
MoH_Vote_Data = pd.merge(MoH_Vote_Data , df_FilmVote, on = "name", how='left')

MoH_Vote_Data.head()

,person_x,name_x,VoteAlong113thRatio_FS_IIR,VoteAlong114thRatio_FS_IIR,VoteAlong115thRatio_FS_IIR,VoteAlong116thRatio_FS_IIR,VoteAlong113thRatio_FS_FSS,VoteAlong114thRatio_FS_FSS,VoteAlong115thRatio_FS_FSS,VoteAlong116thRatio_FS_FSS,...,Session_113_y,Session_114_y,Session_115_y,Session_116_y,person_y,party,VoteAlong113thRatio_Film,VoteAlong114thRatio_Film,VoteAlong115thRatio_Film,VoteAlong116thRatio_Film
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",0.333333,0.6,NaN,NaN,0.333333,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",0.500000,0.8,0.428571,1.0,0.666667,0.333333,0.555556,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",0.500000,NaN,NaN,NaN,0.666667,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",0.333333,0.8,0.428571,1.0,0.333333,0.333333,0.222222,1.0,...,True,True,True,True,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
#MoH_Vote_Data.columns.tolist()

# Clean Data
list = ['person_x',
 'name_x',
 'party_short',
 'Pure_name',
 'LastName',
 'FirstName',
 'ID_NameParty',
 'first_x',
 'last_x',
 'party_x',
 'pageid_x',
 'wikidataid_x',
 'wikititle_x',
 'name_y',
 'sex_x',
 'ethnicity_x',
 'religion_x',
 'birth_x',
 'death_x',
 'birthplace_x',
 'deathplace_x',
 'Number_Sessions_Served_x',
 'Session_113_x',
 'Session_114_x',
 'Session_115_x',
 'Session_116_x',
 'first_y',
 'last_y',
 'party_y',
 'pageid_y',
 'wikidataid_y',
 'wikititle_y',
 'death_y',
 'birthplace_y',
 'deathplace_y',
 'Session_113_y',
 'Session_114_y',
 'Session_115_y',
 'Session_116_y',
 'person_y',]

MoH_Vote_Data = MoH_Vote_Data.drop(columns = list)

In [28]:
# Save Data-Set externally

compression_opts = dict(method='zip',
                        archive_name='MoH_Vote_AllDonors_Data.csv')  
MoH_Vote_Data.to_csv('MoH_Vote_AllDonors_Data.zip', index=False,
          compression=compression_opts)

In [ ]:
# Convert to Long Format