In [53]:

import csv
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [94]:
#Load DataSet that contains all MoH and the Disney Donation Data

xx = "MoH_Vote_AllDonors_Data_New.csv"

df = pd.read_csv(xx)

df.head()

,pageid,party_x,wikidataid,wikititle,name_x,sex,ethnicity,religion,birth,death,...,party_short,Pure_name,LastName,FirstName,name,party_y.1,VoteAlong113thRatio_Film,VoteAlong114thRatio_Film,VoteAlong115thRatio_Film,VoteAlong116thRatio_Film
0,25016198,R,Q4954892,Bradley_Byrne,Bradley Byrne,male,white,NaN,1955-02-16,NaN,...,R,Bradley Byrne,Byrne,Bradley,"Rep. Bradley Byrne [R, 2014-2020]",Republican,0.75,0.666667,0.8,0.0
1,29218153,R,Q439117,Martha_Roby,Martha Roby,female,white,NaN,1976-07-26,NaN,...,R,Martha Roby,Roby,Martha,"Rep. Martha Roby [R, 2011-2020]",Republican,0.75,1.000000,0.6,0.0
2,407888,R,Q693238,Mike_Rogers_(Alabama_politician),Mike D. Rogers,male,white,protestantism baptist,1958-07-16,NaN,...,R,Mike Rogers,Rogers,Mike,"Rep. Mike Rogers [R, 2003-2022]",Republican,0.50,1.000000,0.6,0.5
3,407888,R,Q693238,Mike_Rogers_(Alabama_politician),Mike D. Rogers,male,white,protestantism baptist,1958-07-16,NaN,...,R,Mike Rogers,Rogers,Mike,"Rep. Mike Rogers [R, 2001-2014]",Republican,0.75,NaN,NaN,NaN
4,407889,R,Q672671,Robert_Aderholt,Robert Aderholt,male,white,protestantism methodist,1965-07-22,NaN,...,R,Robert Aderholt,Aderholt,Robert,"Rep. Robert Aderholt [R, 1997-2022]",Republican,1.00,0.666667,0.8,0.0

In [95]:
df.columns.tolist()

['pageid',
 'party_x',
 'wikidataid',
 'wikititle',
 'name_x',
 'sex',
 'ethnicity',
 'religion',
 'birth',
 'death',
 'birthplace',
 'deathplace',
 'Number_Sessions_Served',
 'Session_113',
 'Session_114',
 'Session_115',
 'Session_116',
 'first',
 'last',
 'ID_NameParty',
 'party_y',
 'Bloomberg_donations2012',
 'Bloomberg_donations2014',
 'Bloomberg_donations2016',
 'Bloomberg_donations2018',
 'party_x.1',
 'Citadel_donations2012',
 'Citadel_donations2014',
 'Citadel_donations2016',
 'Citadel_donations2018',
 'person',
 'name_y',
 'VoteAlong113thRatio_FS_IIR',
 'VoteAlong114thRatio_FS_IIR',
 'VoteAlong115thRatio_FS_IIR',
 'VoteAlong116thRatio_FS_IIR',
 'VoteAlong113thRatio_FS_FSS',
 'VoteAlong114thRatio_FS_FSS',
 'VoteAlong115thRatio_FS_FSS',
 'VoteAlong116thRatio_FS_FSS',
 'VoteAlong113thRatio_FS_CM',
 'VoteAlong114thRatio_FS_CM',
 'VoteAlong115thRatio_FS_CM',
 'VoteAlong116thRatio_FS_CM',
 'VoteAlong113thRatio_FS_REB',
 'VoteAlong114thRatio_FS_REB',
 'VoteAlong115thRatio_FS_REB',
 'VoteAlong116thRatio_FS_REB',
 'party_short',
 'Pure_name',
 'LastName',
 'FirstName',
 'name',
 'party_y.1',
 'VoteAlong113thRatio_Film',
 'VoteAlong114thRatio_Film',
 'VoteAlong115thRatio_Film',
 'VoteAlong116thRatio_Film']

In [96]:
list = ['pageid',
 'party_x',
 'wikidataid',
 'wikititle',
 'name_x',
 'religion',
 'birth',
 'death',
 'birthplace',
 'deathplace',
 'Number_Sessions_Served',
 'Session_113',
 'Session_114',
 'Session_115',
 'Session_116',
 'first',
 'last',
 'ID_NameParty',
 'party_y',
 'party_x.1',
 'name_y',
 'Pure_name',
 'LastName',
 'FirstName',
 'name',
 'party_y.1']


df = df.drop(columns = list)

In [97]:
df = df.fillna(0)
df.head()

,sex,ethnicity,Bloomberg_donations2012,Bloomberg_donations2014,Bloomberg_donations2016,Bloomberg_donations2018,Citadel_donations2012,Citadel_donations2014,Citadel_donations2016,Citadel_donations2018,...,VoteAlong116thRatio_FS_CM,VoteAlong113thRatio_FS_REB,VoteAlong114thRatio_FS_REB,VoteAlong115thRatio_FS_REB,VoteAlong116thRatio_FS_REB,party_short,VoteAlong113thRatio_Film,VoteAlong114thRatio_Film,VoteAlong115thRatio_Film,VoteAlong116thRatio_Film
0,male,white,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.000000,0.75,1.0,0.333333,R,0.75,0.666667,0.8,0.0
1,female,white,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.333333,0.75,1.0,0.333333,R,0.75,1.000000,0.6,0.0
2,male,white,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.666667,0.75,1.0,0.333333,R,0.50,1.000000,0.6,0.5
3,male,white,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.666667,0.00,0.0,0.000000,R,0.75,0.000000,0.0,0.0
4,male,white,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,1.000000,1.00,1.0,0.333333,R,1.00,0.666667,0.8,0.0

In [98]:

df.columns.tolist()

['sex',
 'ethnicity',
 'Bloomberg_donations2012',
 'Bloomberg_donations2014',
 'Bloomberg_donations2016',
 'Bloomberg_donations2018',
 'Citadel_donations2012',
 'Citadel_donations2014',
 'Citadel_donations2016',
 'Citadel_donations2018',
 'person',
 'VoteAlong113thRatio_FS_IIR',
 'VoteAlong114thRatio_FS_IIR',
 'VoteAlong115thRatio_FS_IIR',
 'VoteAlong116thRatio_FS_IIR',
 'VoteAlong113thRatio_FS_FSS',
 'VoteAlong114thRatio_FS_FSS',
 'VoteAlong115thRatio_FS_FSS',
 'VoteAlong116thRatio_FS_FSS',
 'VoteAlong113thRatio_FS_CM',
 'VoteAlong114thRatio_FS_CM',
 'VoteAlong115thRatio_FS_CM',
 'VoteAlong116thRatio_FS_CM',
 'VoteAlong113thRatio_FS_REB',
 'VoteAlong114thRatio_FS_REB',
 'VoteAlong115thRatio_FS_REB',
 'VoteAlong116thRatio_FS_REB',
 'party_short',
 'VoteAlong113thRatio_Film',
 'VoteAlong114thRatio_Film',
 'VoteAlong115thRatio_Film',
 'VoteAlong116thRatio_Film']

In [99]:
# recode_sessions = ["lcycle1", ["lcycle2"], ['lcycle3'],["lcycle4"]]
# recode_donations = ["dcycle1", "dcycle2", 'dcycle3'],["dcycle4"]]
# old_donor_columns = [['donations2012'], ['donations2014'], ['donations2016'],['donations2018']]
# df[recode_donations] = df[old_donor_columns]

#df.rename(columns = {'disney_donations2012': "d2012", "disney_donations2014": "d2014", "disney_donations2016":"d2016", "disney_donations2018":"d2018"}, inplace = True)

df.rename(columns = {'Bloomberg_donations2012': "b2012", "Bloomberg_donations2014": "b2014", "Bloomberg_donations2016":"b2016", "Bloomberg_donations2018":"b2018"}, inplace = True)

df.rename(columns = {'Citadel_donations2012': "t2012", "Citadel_donations2014": "t2014", "Citadel_donations2016":"t2016", "Citadel_donations2018":"t2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_Film': "f2012", "VoteAlong114thRatio_Film": "f2014", "VoteAlong115thRatio_Film":"f2016", "VoteAlong116thRatio_Film":"f2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_IIR': "i2012", "VoteAlong114thRatio_FS_IIR": "i2014", "VoteAlong115thRatio_FS_IIR":"i2016", "VoteAlong116thRatio_FS_IIR":"i2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_FSS': "s2012", "VoteAlong114thRatio_FS_FSS": "s2014", "VoteAlong115thRatio_FS_FSS":"s2016", "VoteAlong116thRatio_FS_FSS":"s2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_CM': "c2012", "VoteAlong114thRatio_FS_CM": "c2014", "VoteAlong115thRatio_FS_CM":"c2016", "VoteAlong116thRatio_FS_CM":"c2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_REB': "r2012", "VoteAlong114thRatio_FS_REB": "r2014", "VoteAlong115thRatio_FS_REB":"r2016", "VoteAlong116thRatio_FS_REB":"r2018"}, inplace = True)

In [20]:
df.dtypes

person_x                    int64
name                       object
i2012                     float64
i2014                     float64
i2016                     float64
i2018                     float64
s2012                     float64
s2014                     float64
s2016                     float64
s2018                     float64
c2012                     float64
c2014                     float64
c2016                     float64
c2018                     float64
r2012                     float64
r2014                     float64
r2016                     float64
r2018                     float64
party_short                object
Pure_name                  object
LastName                   object
FirstName                  object
ID_NameParty               object
first                      object
last                       object
party_x                    object
pageid                    float64
wikidataid                 object
wikititle                  object
name_y                     object
sex                        object
ethnicity                  object
religion                   object
birth                      object
death                     float64
birthplace                 object
deathplace                float64
Number_Sessions_Served    float64
Session_113                object
Session_114                object
Session_115                object
Session_116                object
d2012                     float64
d2014                     float64
d2016                     float64
d2018                     float64
person_y                  float64
party_y                    object
f2012                     float64
f2014                     float64
f2016                     float64
f2018                     float64
dtype: object

In [100]:
df["person"] = df.index
df_long = pd.wide_to_long(df, [ "f", "i", "s", "c", "r", "b", "t"], i="person", j="Year")

df_long.rename(columns = { "f":"VoteAlongRatio_Film", "i":"VoteAlongRatio_FS_IIR", "s":"VoteAlongRatio_FS_FSS", "c":"VoteAlongRatio_FS_CM", "r":"VoteAlongRatio_FS_REB", "b":"Bloomberg_Donations","t":"Citadel_Donations", }, inplace = True)

In [101]:
df_long.head(5)

,,party_short,ethnicity,sex,VoteAlongRatio_Film,VoteAlongRatio_FS_IIR,VoteAlongRatio_FS_FSS,VoteAlongRatio_FS_CM,VoteAlongRatio_FS_REB,Bloomberg_Donations,Citadel_Donations
person,Year,,,,,,,,,,
0,2012,R,white,male,0.75,0.000000,0.000000,0.000000,0.000000,0.0,0.0
1,2012,R,white,female,0.75,0.833333,0.666667,0.714286,0.333333,0.0,0.0
2,2012,R,white,male,0.50,0.833333,0.333333,0.714286,0.666667,0.0,0.0
3,2012,R,white,male,0.75,0.833333,0.666667,0.714286,0.666667,0.0,0.0
4,2012,R,white,male,1.00,1.000000,1.000000,0.571429,1.000000,0.0,0.0

In [102]:
df_long.reset_index(inplace=True)

#missing values for predicotr variable means no vote, which will be classified as against party lines
#df_long = df_long.fillna(0)

#  df_long.isnull().sum()

In [103]:
df_long_sorted = df_long.sort_values(by=['person',"Year"])
df_long_sorted.head()

,person,Year,party_short,ethnicity,sex,VoteAlongRatio_Film,VoteAlongRatio_FS_IIR,VoteAlongRatio_FS_FSS,VoteAlongRatio_FS_CM,VoteAlongRatio_FS_REB,Bloomberg_Donations,Citadel_Donations
0,0,2012,R,white,male,0.750000,0.000000,0.000000,0.000000,0.000000,0.0,0.0
278,0,2014,R,white,male,0.666667,0.800000,0.333333,0.600000,0.750000,0.0,0.0
556,0,2016,R,white,male,0.800000,0.857143,0.888889,1.000000,1.000000,0.0,0.0
834,0,2018,R,white,male,0.000000,0.500000,0.333333,1.000000,0.333333,0.0,0.0
1,1,2012,R,white,female,0.750000,0.833333,0.666667,0.714286,0.333333,0.0,0.0

In [104]:
# Set NaN to Zeros 
df_long_sorted = df_long_sorted.fillna(0)

In [105]:
#lag the predictor variable
#df_long_sorted['disney_donations_lagMinus1'] = df_long.groupby('person')['disney_donations'].shift(-1)
df_long_sorted['Bloomberg_donations_lagMinus1'] = df_long.groupby('person')['Bloomberg_Donations'].shift(-1)
df_long_sorted['Citadel_donations_lagMinus1'] = df_long.groupby('person')['Citadel_Donations'].shift(-1)


df_long_sorted.head(150)

,person,Year,party_short,ethnicity,sex,VoteAlongRatio_Film,VoteAlongRatio_FS_IIR,VoteAlongRatio_FS_FSS,VoteAlongRatio_FS_CM,VoteAlongRatio_FS_REB,Bloomberg_Donations,Citadel_Donations,Bloomberg_donations_lagMinus1,Citadel_donations_lagMinus1
0,0,2012,R,white,male,0.750000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.0,0.0
278,0,2014,R,white,male,0.666667,0.800000,0.333333,0.600000,0.750000,0.0,0.0,0.0,0.0
556,0,2016,R,white,male,0.800000,0.857143,0.888889,1.000000,1.000000,0.0,0.0,0.0,0.0
834,0,2018,R,white,male,0.000000,0.500000,0.333333,1.000000,0.333333,0.0,0.0,NaN,NaN
1,1,2012,R,white,female,0.750000,0.833333,0.666667,0.714286,0.333333,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
314,36,2014,D,hispanic,female,0.666667,0.800000,0.333333,0.400000,0.250000,0.0,0.0,0.0,0.0
592,36,2016,D,hispanic,female,0.600000,0.285714,0.444444,0.500000,0.666667,0.0,0.0,0.0,0.0
870,36,2018,D,hispanic,female,0.500000,0.750000,1.000000,1.000000,1.000000,0.0,0.0,NaN,NaN
37,37,2012,D,hispanic,male,0.500000,0.666667,0.666667,0.714286,0.666667,0.0,0.0,0.0,0.0
315,37,2014,D,hispanic,male,0.666667,0.800000,0.333333,0.600000,0.250000,0.0,0.0,0.0,0.0

In [106]:
MoH_Vote_Data_Long_Sorted = df_long_sorted

In [107]:
# Save Data-Set externally

compression_opts = dict(method='zip',
                        archive_name='MoH_Vote_AllDonors_Data_Long_Sorted_New.csv')  
MoH_Vote_Data_Long_Sorted.to_csv('MoH_Vote_AllDonors_Data_Long_Sorted_New.zip', index=False,
          compression=compression_opts)

In [ ]:
#-----------------------------------------------------
# ----------------- Ideenspeicher----------------------
#-----------------------------------------------------

In [26]:
#create a list of all unique IDs
ids=df_long
data_id=ids.drop_duplicates(subset='person')
data_id=data_id[['person']]
data_id.shape

(224, 1)

In [27]:
#create new variable with random number between one and zero
np.random.seed(42)
data_id['data_use'] = (np.random.randint(0, 10000, data_id.shape[0]))/10000
data_id=data_id[['person', 'data_use']]

In [28]:
#assign each person to a modeling group training or testing with a 50 percent chance 

data_id['MODELING_GROUP'] = np.where(((data_id.data_use <= 0.55)), 'TRAINING', 'TESTING')

In [29]:

groups = data_id.groupby(['MODELING_GROUP'])['person'].count()
groups

MODELING_GROUP
TESTING     108
TRAINING    116
Name: person, dtype: int64

In [30]:
df_long_lagged=df_long_lagged.sort_values(by=['person'], ascending=[True])
data_id=data_id.sort_values(by=['person'], ascending=[True])
df_long_modelgroups_lagged =df_long_lagged.merge(data_id, on=['person'], how='inner')
df_long_modelgroups_lagged.head()

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP
0,4,2012,D,0.0,0.000000,0.0,0.727,TESTING
1,4,2014,D,0.0,0.333333,0.0,0.727,TESTING
2,4,2016,D,0.0,0.400000,1000.0,0.727,TESTING
3,4,2018,D,1000.0,1.000000,NaN,0.727,TESTING
4,10,2012,D,0.0,0.500000,2000.0,0.086,TRAINING

In [31]:
df_long_modelgroups_lagged.head(50)

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP
0,4,2012,D,0.0,0.000000,0.0,0.7270,TESTING
1,4,2014,D,0.0,0.333333,0.0,0.7270,TESTING
2,4,2016,D,0.0,0.400000,1000.0,0.7270,TESTING
3,4,2018,D,1000.0,1.000000,NaN,0.7270,TESTING
4,10,2012,D,0.0,0.500000,2000.0,0.0860,TRAINING
5,10,2014,D,2000.0,0.666667,2000.0,0.0860,TRAINING
6,10,2016,D,2000.0,0.600000,1000.0,0.0860,TRAINING
7,10,2018,D,1000.0,1.000000,NaN,0.0860,TRAINING
8,12,2012,D,0.0,0.250000,0.0,0.5390,TRAINING
9,12,2014,D,0.0,1.000000,0.0,0.5390,TRAINING
10,12,2016,D,0.0,0.800000,0.0,0.5390,TRAINING
11,12,2018,D,0.0,1.000000,NaN,0.5390,TRAINING
12,14,2018,D,3700.0,0.000000,NaN,0.5191,TRAINING
13,14,2016,D,0.0,0.400000,3700.0,0.5191,TRAINING
14,14,2012,D,0.0,0.250000,0.0,0.5191,TRAINING
15,14,2014,D,0.0,0.333333,0.0,0.5191,TRAINING
16,15,2012,D,0.0,0.000000,0.0,0.5734,TESTING
17,15,2014,D,0.0,0.000000,0.0,0.5734,TESTING
18,15,2016,D,0.0,0.200000,0.0,0.5734,TESTING
19,15,2018,D,0.0,1.000000,NaN,0.5734,TESTING
20,16,2018,D,0.0,1.000000,NaN,0.6265,TESTING
21,16,2012,D,0.0,0.500000,0.0,0.6265,TESTING
22,16,2014,D,0.0,0.333333,0.0,0.6265,TESTING
23,16,2016,D,0.0,0.800000,0.0,0.6265,TESTING
24,17,2018,D,0.0,1.000000,NaN,0.0466,TRAINING
25,17,2016,D,0.0,0.800000,0.0,0.0466,TRAINING
26,17,2012,D,0.0,0.000000,0.0,0.0466,TRAINING
27,17,2014,D,0.0,0.333333,0.0,0.0466,TRAINING
28,18,2012,D,0.0,0.000000,1000.0,0.4426,TRAINING
29,18,2014,D,1000.0,0.333333,0.0,0.4426,TRAINING
30,18,2016,D,0.0,0.600000,0.0,0.4426,TRAINING
31,18,2018,D,0.0,1.000000,NaN,0.4426,TRAINING
32,19,2012,D,0.0,0.000000,0.0,0.5578,TESTING
33,19,2014,D,0.0,0.333333,0.0,0.5578,TESTING
34,19,2016,D,0.0,0.800000,80.0,0.5578,TESTING
35,19,2018,D,80.0,1.000000,NaN,0.5578,TESTING
36,21,2018,D,0.0,1.000000,NaN,0.8322,TESTING
37,21,2016,D,0.0,0.400000,0.0,0.8322,TESTING
38,21,2014,D,0.0,0.333333,0.0,0.8322,TESTING
39,21,2012,D,250.0,0.000000,0.0,0.8322,TESTING
40,22,2012,D,0.0,0.500000,0.0,0.1685,TRAINING
41,22,2014,D,0.0,0.333333,0.0,0.1685,TRAINING
42,22,2016,D,0.0,0.800000,0.0,0.1685,TRAINING
43,22,2018,D,0.0,0.000000,NaN,0.1685,TRAINING
44,23,2012,D,0.0,0.250000,0.0,0.0769,TRAINING
45,23,2014,D,0.0,0.333333,0.0,0.0769,TRAINING
46,23,2016,D,0.0,0.400000,0.0,0.0769,TRAINING
47,23,2018,D,0.0,1.000000,NaN,0.0769,TRAINING
48,24,2016,D,0.0,0.800000,0.0,0.6949,TESTING
49,24,2018,D,0.0,1.000000,NaN,0.6949,TESTING

In [32]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [33]:
df_long_modelgroups_lagged['democrat'] = np.where(df_long_modelgroups_lagged['party_short'] == "D", 1, 0)
df_long_modelgroups_lagged.head()

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP,democrat
0,4,2012,D,0.0,0.000000,0.0,0.727,TESTING,1
1,4,2014,D,0.0,0.333333,0.0,0.727,TESTING,1
2,4,2016,D,0.0,0.400000,1000.0,0.727,TESTING,1
3,4,2018,D,1000.0,1.000000,NaN,0.727,TESTING,1
4,10,2012,D,0.0,0.500000,2000.0,0.086,TRAINING,1

In [34]:
!pip install linearmodels

Requirement already satisfied: linearmodels in c:\users\jmitc\anaconda3\lib\site-packages (4.23)
Requirement already satisfied: numpy>=1.16 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.19.1)
Requirement already satisfied: patsy in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.5.1)
Requirement already satisfied: mypy-extensions>=0.4 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.4.3)
Requirement already satisfied: statsmodels>=0.11 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.12.0)
Requirement already satisfied: pandas>=0.24 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.1.3)
Requirement already satisfied: pyhdfe>=0.1 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.1.0)
Requirement already satisfied: property-cached>=1.6.3 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.6.4)
Requirement already satisfied: scipy>=1.2 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.5.0)
Requirement already satisfied: Cython>=0.29.21 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.29.21)
Requirement already satisfied: six in c:\users\jmitc\anaconda3\lib\site-packages (from patsy->linearmodels) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\jmitc\anaconda3\lib\site-packages (from pandas>=0.24->linearmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\jmitc\anaconda3\lib\site-packages (from pandas>=0.24->linearmodels) (2020.1)

In [35]:
from linearmodels import PanelOLS as pols
import statsmodels.api as sm

In [36]:
df_long_modelgroups_lagged["Year"] =  pd.to_datetime(df_long_modelgroups_lagged['Year'], format='%Y')

In [37]:
df_long_modelgroups_lagged = df_long_modelgroups_lagged.set_index(['person', "Year"], drop=True)

In [38]:
df_long_modelgroups_lagged.head()

                  party_short  donations_dollars  partyline_percent  \
person Year
4      2012-01-01           D                0.0           0.000000
       2014-01-01           D                0.0           0.333333
       2016-01-01           D                0.0           0.400000
       2018-01-01           D             1000.0           1.000000
10     2012-01-01           D                0.0           0.500000

                   donations_dollars_lag  data_use MODELING_GROUP  democrat
person Year
4      2012-01-01                    0.0     0.727        TESTING         1
       2014-01-01                    0.0     0.727        TESTING         1
       2016-01-01                 1000.0     0.727        TESTING         1
       2018-01-01                    NaN     0.727        TESTING         1
10     2012-01-01                 2000.0     0.086       TRAINING         1

In [45]:
exog_vars = ["partyline_percent"]

mod = pols(df_long_modelgroups_lagged.donations_dollars_lag,df_long_modelgroups_lagged['partyline_percent'], 
           time_effects = True,entity_effects = True)
pooled_res = mod.fit()
print(pooled_res)

                            PanelOLS Estimation Summary
===================================================================================
Dep. Variable:     donations_dollars_lag   R-squared:                     1.961e-06
Estimator:                      PanelOLS   R-squared (Between):             -0.0027
No. Observations:                    672   R-squared (Within):           -9.305e-05
Date:                   Mon, Mar 29 2021   R-squared (Overall):             -0.0017
Time:                           21:10:57   Log-likelihood                   -5852.0
Cov. Estimator:               Unadjusted
                                           F-statistic:                      0.0009
Entities:                            224   P-value                           0.9764
Avg Obs:                          3.0000   Distribution:                   F(1,445)
Min Obs:                          3.0000
Max Obs:                          3.0000   F-statistic (robust):             0.0009
                                           P-value                           0.9764
Time periods:                          3   Distribution:                   F(1,445)
Avg Obs:                          224.00
Min Obs:                          224.00
Max Obs:                          224.00

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
partyline_percent    -13.553     458.77    -0.0295     0.9764     -915.17      888.07
=====================================================================================

F-test for Poolability: 2.7117
P-value: 0.0000
Distribution: F(225,445)

Included effects: Entity, Time

In [48]:
test = mod.predict(train_df[exog_vars], data=df_long_modelgroups_lagged, exog=None)

ValueError: Unable to use data when the model was not created using a formula.

In [49]:
df_long_modelgroups_lagged.to_csv(r'C:\Users\jmitc\rollcall\walt_disney_PANELMODEL.csv',index = True)

In [41]:
train_df = df_long_modelgroups_lagged[df_long_modelgroups_lagged.MODELING_GROUP=="TRAINING"]
test_df = df_long_modelgroups_lagged[df_long_modelgroups_lagged.MODELING_GROUP=="TESTING"]

In [42]:
train_model = pols(train_df['donations_dollars_lag'],train_df[exog_vars], entity_effects = True, 
                   time_effects = True)
train_fit_vals = train_model.fit()

In [43]:
train_fit_vals

                            PanelOLS Estimation Summary
===================================================================================
Dep. Variable:     donations_dollars_lag   R-squared:                        0.0005
Estimator:                      PanelOLS   R-squared (Between):             -0.0462
No. Observations:                    348   R-squared (Within):               0.0005
Date:                   Mon, Mar 29 2021   R-squared (Overall):             -0.0298
Time:                           21:08:25   Log-likelihood                   -2959.1
Cov. Estimator:               Unadjusted
                                           F-statistic:                      0.1200
Entities:                            116   P-value                           0.7293
Avg Obs:                          3.0000   Distribution:                   F(1,229)
Min Obs:                          3.0000
Max Obs:                          3.0000   F-statistic (robust):             0.1200
                                           P-value                           0.7293
Time periods:                          3   Distribution:                   F(1,229)
Avg Obs:                          116.00
Min Obs:                          116.00
Max Obs:                          116.00

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
partyline_percent    -177.52     512.40    -0.3465     0.7293     -1187.2      832.11
=====================================================================================

F-test for Poolability: 3.0404
P-value: 0.0000
Distribution: F(117,229)

Included effects: Entity, Time
PanelEffectsResults, id: 0x1e205cd6b50

In [44]:
train_predictions = train_model.predict(train_df[exog_vars])

AssertionError: