In [1]:
import numpy as np
import pandas as pd

In [2]:
# Loading data
a = "Disney_Donor_Vote.csv"
df = pd.read_csv(a)

In [3]:
df.head(50)

,person,name_x,party_x,VoteAlong113thRatio,VoteAlong114thRatio,VoteAlong115thRatio,VoteAlong116thRatio,party_short,Last_name,Suffix,...,religion,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,N,Robert “Rob” Andrews,Andrews,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",Democrat,0.00,0.666667,NaN,NaN,D,Xavier Becerra,Becerra,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",Democrat,0.75,0.333333,0.6,1.0,D,Sanford Bishop,Bishop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",Democrat,0.50,NaN,NaN,NaN,D,Timothy Bishop,Bishop,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",Democrat,0.00,0.333333,0.4,1.0,D,Earl Blumenauer,Blumenauer,...,NaN,1948-08-16,NaN,"45.51667,-122.66667",NaN,4.0,True,True,True,True
5,400047,"Rep. Robert Brady [D, 1998-2018]",Democrat,0.50,0.333333,0.8,NaN,D,Robert Brady,Brady,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,400048,"Rep. Corrine Brown [D, 2013-2016]",Democrat,0.50,0.666667,NaN,NaN,D,Corrine Brown,Brown,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,400062,"Rep. Lois Capps [D, 2013-2016]",Democrat,0.25,0.000000,NaN,NaN,D,Lois Capps,Capps,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,400063,"Rep. Michael Capuano [D, 2013-2018]",Democrat,0.25,0.333333,0.6,NaN,D,Michael Capuano,Capuano,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,400074,"Rep. Lacy Clay Jr. [D, 2001-2020]",Democrat,0.50,0.333333,0.6,0.5,D,Lacy Clay,Clay,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,400075,"Rep. James “Jim” Clyburn [D, 1993-2022]",Democrat,0.50,0.666667,0.6,1.0,D,James “Jim” Clyburn,Clyburn,...,protestantism methodist,1940-07-21,NaN,"33.92056,-80.34472",NaN,4.0,True,True,True,True
11,400080,"Rep. John Conyers Jr. [D, 2013-2017]",Democrat,0.00,0.333333,NaN,NaN,D,John Conyers,Conyers,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,400081,"Rep. Jim Cooper [D, 2003-2022]",Democrat,0.25,1.000000,0.8,1.0,D,Jim Cooper,Cooper,...,anglicanism,1954-06-19,NaN,"36.165,-86.78389",NaN,4.0,True,True,True,True
13,400087,"Rep. Joseph “Joe” Crowley [D, 2013-2018]",Democrat,0.50,0.333333,0.4,NaN,D,Joseph “Joe” Crowley,Crowley,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,400090,"Rep. Elijah Cummings [D, 1996-2019]",Democrat,0.25,0.333333,0.4,NaN,D,Elijah Cummings,Cummings,...,protestantism baptist,1951-01-18,NaN,"39.28639,-76.615",NaN,4.0,True,True,True,True
15,400093,"Rep. Danny Davis [D, 1997-2022]",Democrat,0.00,0.000000,0.2,1.0,D,Danny Davis,Davis,...,protestantism baptist,1941-09-06,NaN,"33.12167,-91.5475",NaN,4.0,True,True,True,True
16,400097,"Rep. Susan Davis [D, 2003-2020]",Democrat,0.50,0.333333,0.8,1.0,D,Susan Davis,Davis,...,judaism,1944-04-13,NaN,"42.375,-71.10611",NaN,4.0,True,True,True,True
17,400100,"Rep. Peter DeFazio [D, 1987-2022]",Democrat,0.00,0.333333,0.8,1.0,D,Peter DeFazio,DeFazio,...,catholicism,1947-05-27,NaN,"42.28333,-71.23333",NaN,4.0,True,True,True,True
18,400101,"Rep. Diana DeGette [D, 1997-2022]",Democrat,0.00,0.333333,0.6,1.0,D,Diana DeGette,DeGette,...,protestantism reformed,1957-07-29,NaN,"35.69389,139.41944",NaN,4.0,True,True,True,True
19,400103,"Rep. Rosa DeLauro [D, 1991-2022]",Democrat,0.00,0.333333,0.8,1.0,D,Rosa DeLauro,DeLauro,...,catholicism,1943-03-02,NaN,"41.30833,-72.925",NaN,4.0,True,True,True,True
20,400110,"Rep. John Dingell [D, 2013-2014]",Democrat,0.25,NaN,NaN,NaN,D,John Dingell,Dingell,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,400111,"Rep. Lloyd Doggett [D, 2013-2022]",Democrat,0.00,0.333333,0.4,1.0,D,Lloyd Doggett,Doggett,...,protestantism methodist,1946-10-06,NaN,"30.3,-97.73333",NaN,4.0,True,True,True,True
22,400114,"Rep. Michael Doyle [D, 2003-2018]",Democrat,0.50,0.333333,0.8,NaN,D,Michael Doyle,Doyle,...,catholicism,1953-08-05,NaN,"40.42222,-79.88611",NaN,4.0,True,True,True,True
23,400122,"Rep. Eliot Engel [D, 2013-2020]",Democrat,0.25,0.333333,0.4,1.0,D,Eliot Engel,Engel,...,judaism,1947-02-18,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True
24,400124,"Rep. Anna Eshoo [D, 2013-2022]",Democrat,0.00,0.333333,0.8,1.0,D,Anna Eshoo,Eshoo,...,catholicism,1942-12-13,NaN,"41.675,-72.78722",NaN,4.0,True,True,True,True
25,400129,"Rep. Sam Farr [D, 2013-2016]",Democrat,0.50,0.333333,NaN,NaN,D,Sam Farr,Farr,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,400130,"Rep. Chaka Fattah [D, 1995-2016]",Democrat,0.50,0.666667,NaN,NaN,D,Chaka Fattah,Fattah,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,400160,"Rep. Gene Green [D, 1993-2018]",Democrat,0.50,0.666667,0.8,NaN,D,Gene Green,Green,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,400162,"Rep. Raúl Grijalva [D, 2013-2022]",Democrat,0.00,0.333333,0.4,1.0,D,Raúl Grijalva,Grijalva,...,catholicism,1948-02-19,NaN,"32.22167,-110.92639",NaN,4.0,True,True,True,True
29,400163,"Rep. Luis Gutiérrez [D, 1993-2018]",Democrat,0.00,0.333333,0.4,NaN,D,Luis Gutiérrez,Gutiérrez,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,400170,"Rep. Alcee Hastings [D, 2013-2022]",Democrat,0.00,0.666667,0.8,1.0,D,Alcee Hastings,Hastings,...,protestantism methodist,1936-09-05,NaN,"28.66139,-81.39194",NaN,4.0,True,True,True,True
31,400179,"Rep. Rubén Hinojosa [D, 1997-2016]",Democrat,0.25,0.666667,NaN,NaN,D,Rubén Hinojosa,Hinojosa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,400184,"Rep. Rush Holt [D, 1999-2014]",Democrat,0.00,NaN,NaN,NaN,D,Rush Holt,Holt,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,400185,"Rep. Michael “Mike” Honda [D, 2013-2016]",Democrat,0.25,0.333333,NaN,NaN,D,Michael “Mike” Honda,Honda,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,400189,"Rep. Steny Hoyer [D, 1981-2022]",Democrat,0.50,0.666667,0.6,1.0,D,Steny Hoyer,Hoyer,...,protestantism baptist,1939-06-14,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True
35,400195,"Rep. Steve Israel [D, 2013-2016]",Democrat,0.25,0.333333,NaN,NaN,D,Steve Israel,Israel,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,400199,"Rep. Sheila Jackson Lee [D, 1995-2022]",Democrat,0.25,0.333333,0.6,1.0,D,Sheila Jackson Lee,Lee,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,400204,"Rep. Eddie Johnson [D, 1993-2022]",Democrat,0.25,0.333333,0.8,0.5,D,Eddie Johnson,Johnson,...,protestantism baptist,1935-12-03,NaN,"31.55139,-97.15583",NaN,4.0,True,True,True,True
38,400211,"Rep. Marcy Kaptur [D, 1983-2022]",Democrat,0.50,0.333333,0.8,1.0,D,Marcy Kaptur,Kaptur,...,catholicism,1946-06-17,NaN,"41.66667,-83.58333",NaN,4.0,True,True,True,True
39,400218,"Rep. Ron Kind [D, 1997-2022]",Democrat,0.50,0.333333,0.2,1.0,D,Ron Kind,Kind,...,protestantism lutheran,1963-03-16,NaN,"43.81333,-91.23306",NaN,4.0,True,True,True,True
40,400230,"Rep. James “Jim” Langevin [D, 2001-2022]",Democrat,0.25,0.333333,0.8,1.0,D,James “Jim” Langevin,Langevin,...,catholicism,1964-04-22,NaN,"41.83083,-71.415",NaN,4.0,True,True,True,True
41,400232,"Rep. Rick Larsen [D, 2001-2022]",Democrat,0.25,0.333333,0.8,1.0,D,Rick Larsen,Larsen,...,protestantism methodist,1965-06-15,NaN,"48.1811,-122.139",NaN,4.0,True,True,True,True
42,400233,"Rep. John Larson [D, 1999-2022]",Democrat,0.25,0.333333,0.8,1.0,D,John Larson,Larson,...,catholicism,1948-07-22,NaN,"41.76333,-72.685",NaN,4.0,True,True,True,True
43,400237,"Rep. Barbara Lee [D, 2013-2022]",Democrat,0.00,0.333333,0.6,1.0,D,Barbara Lee,Lee,...,protestantism baptist,1946-07-16,NaN,"31.79028,-106.42333",NaN,4.0,True,True,True,True
44,400238,"Rep. Sander Levin [D, 2013-2018]",Democrat,0.25,0.333333,0.8,NaN,D,Sander Levin,Levin,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,400240,"Rep. John Lewis [D, 1987-2020]",Democrat,0.00,0.333333,0.6,0.5,D,John Lewis,Lewis,...,protestantism baptist,1940-02-21,NaN,"31.80196,-85.96732",NaN,4.0,True,True,True,True
46,400245,"Rep. Zoe Lofgren [D, 2013-2022]",Democrat,0.00,0.333333,0.4,0.5,D,Zoe Lofgren,Lofgren,...,protestantism lutheran,1947-12-21,NaN,"37.55417,-122.31306",NaN,4.0,True,True,True,True
47,400246,"Rep. Nita Lowey [D, 2013-2020]",Democrat,0.50,0.333333,0.8,1.0,D,Nita Lowey,Lowey,...,judaism,1937-07-05,NaN,"40.67,-73.94",NaN,4.0,True,True,True,True
48,400249,"Rep. Stephen Lynch [D, 2013-2022]",Democrat,0.25,0.333333,0.8,1.0,D,Stephen Lynch,Lynch,...,catholicism,1955-03-31,NaN,"42.35778,-71.06167",NaN,4.0,True,True,True,True
49,400251,"Rep. Carolyn Maloney [D, 2013-2022]",Democrat,0.25,0.333333,0.6,1.0,D,Carolyn Maloney,Maloney,...,protestantism reformed,1946-02-19,NaN,"36.08,-79.81944",NaN,4.0,True,True,True,True

In [4]:
df.columns.tolist()

['person',
 'name_x',
 'party_x',
 'VoteAlong113thRatio',
 'VoteAlong114thRatio',
 'VoteAlong115thRatio',
 'VoteAlong116thRatio',
 'party_short',
 'Last_name',
 'Suffix',
 'LastName',
 'ID_NameParty',
 'Pure_name',
 'FirstName',
 'first',
 'last',
 'party_y',
 'donations2012',
 'donations2014',
 'donations2016',
 'donations2018',
 'pageid',
 'wikidataid',
 'wikititle',
 'name_y',
 'sex',
 'ethnicity',
 'religion',
 'birth',
 'death',
 'birthplace',
 'deathplace',
 'Number_Sessions_Served',
 'Session_113',
 'Session_114',
 'Session_115',
 'Session_116']

In [5]:
df.drop(df[df.Number_Sessions_Served != 4.0].index, inplace=True)
recode = ['donations2012', 'donations2014', 'donations2016','donations2018']
df[recode] = df[recode].fillna(0)

In [6]:
df.head()

,person,name_x,party_x,VoteAlong113thRatio,VoteAlong114thRatio,VoteAlong115thRatio,VoteAlong116thRatio,party_short,Last_name,Suffix,...,religion,birth,death,birthplace,deathplace,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",Democrat,0.00,0.333333,0.4,1.0,D,Earl Blumenauer,Blumenauer,...,NaN,1948-08-16,NaN,"45.51667,-122.66667",NaN,4.0,True,True,True,True
10,400075,"Rep. James “Jim” Clyburn [D, 1993-2022]",Democrat,0.50,0.666667,0.6,1.0,D,James “Jim” Clyburn,Clyburn,...,protestantism methodist,1940-07-21,NaN,"33.92056,-80.34472",NaN,4.0,True,True,True,True
12,400081,"Rep. Jim Cooper [D, 2003-2022]",Democrat,0.25,1.000000,0.8,1.0,D,Jim Cooper,Cooper,...,anglicanism,1954-06-19,NaN,"36.165,-86.78389",NaN,4.0,True,True,True,True
14,400090,"Rep. Elijah Cummings [D, 1996-2019]",Democrat,0.25,0.333333,0.4,NaN,D,Elijah Cummings,Cummings,...,protestantism baptist,1951-01-18,NaN,"39.28639,-76.615",NaN,4.0,True,True,True,True
15,400093,"Rep. Danny Davis [D, 1997-2022]",Democrat,0.00,0.000000,0.2,1.0,D,Danny Davis,Davis,...,protestantism baptist,1941-09-06,NaN,"33.12167,-91.5475",NaN,4.0,True,True,True,True

In [7]:
#this should drop all observations that

In [8]:
df.shape

(224, 37)

In [9]:
df.head()
df.shape

(224, 37)

In [10]:
# recode_sessions = ["lcycle1", ["lcycle2"], ['lcycle3'],["lcycle4"]]
# recode_donations = ["dcycle1", "dcycle2", 'dcycle3'],["dcycle4"]]
# old_donor_columns = [['donations2012'], ['donations2014'], ['donations2016'],['donations2018']]
# df[recode_donations] = df[old_donor_columns]

df.rename(columns = {'donations2012': "d2012", "donations2014": "d2014", "donations2016":"d2016", "donations2018":"d2018"}, inplace = True)
df.rename(columns = {'VoteAlong113thRatio': "l2012", "VoteAlong114thRatio": "l2014", "VoteAlong115thRatio":"l2016", "VoteAlong116thRatio":"l2018"}, inplace = True)

In [11]:
df.dtypes

person                      int64
name_x                     object
party_x                    object
l2012                     float64
l2014                     float64
l2016                     float64
l2018                     float64
party_short                object
Last_name                  object
Suffix                     object
LastName                   object
ID_NameParty               object
Pure_name                  object
FirstName                  object
first                      object
last                       object
party_y                    object
d2012                     float64
d2014                     float64
d2016                     float64
d2018                     float64
pageid                    float64
wikidataid                 object
wikititle                  object
name_y                     object
sex                        object
ethnicity                  object
religion                   object
birth                      object
death                     float64
birthplace                 object
deathplace                float64
Number_Sessions_Served    float64
Session_113                object
Session_114                object
Session_115                object
Session_116                object
dtype: object

In [12]:
df_forlong = df[['person',
                "l2012", "l2014",'l2016',"l2018",
                "d2012", "d2014",'d2016',"d2018",
                "party_short"]].copy()

In [13]:
df_forlong.head()

,person,l2012,l2014,l2016,l2018,d2012,d2014,d2016,d2018,party_short
4,400033,0.00,0.333333,0.4,1.0,0.0,0.0,0.0,1000.0,D
10,400075,0.50,0.666667,0.6,1.0,0.0,2000.0,2000.0,1000.0,D
12,400081,0.25,1.000000,0.8,1.0,0.0,0.0,0.0,0.0,D
14,400090,0.25,0.333333,0.4,NaN,0.0,0.0,0.0,3700.0,D
15,400093,0.00,0.000000,0.2,1.0,0.0,0.0,0.0,0.0,D

In [14]:
df_forlong["person"] = df.index
df_long = pd.wide_to_long(df_forlong, ["d", "l"], i="person", j="Year")

df_long.rename(columns = {'d':"donations_dollars", "l":"partyline_percent"}, inplace = True)

In [15]:
df_long.value_counts

<bound method DataFrame.value_counts of             party_short  donations_dollars  partyline_percent
person Year
4      2012           D                0.0               0.00
10     2012           D                0.0               0.50
12     2012           D                0.0               0.25
14     2012           D                0.0               0.25
15     2012           D                0.0               0.00
...                 ...                ...                ...
540    2018           R                0.0               0.00
588    2018           D                0.0               1.00
654    2018           R                0.0               0.00
656    2018           R             2000.0               0.00
660    2018           R                0.0               0.00

[896 rows x 3 columns]>

In [16]:
# df_long.to_csv(r'C:\Users\jmitc\rollcall\walt_data_long.csv',index = True)

In [17]:
df_long.head()

            party_short  donations_dollars  partyline_percent
person Year
4      2012           D                0.0               0.00
10     2012           D                0.0               0.50
12     2012           D                0.0               0.25
14     2012           D                0.0               0.25
15     2012           D                0.0               0.00

In [18]:
df_long.reset_index(inplace=True)

In [19]:
df_long.head(250)

     person  Year party_short  donations_dollars  partyline_percent
0         4  2012           D                0.0           0.000000
1        10  2012           D                0.0           0.500000
2        12  2012           D                0.0           0.250000
3        14  2012           D                0.0           0.250000
4        15  2012           D                0.0           0.000000
..      ...   ...         ...                ...                ...
245      42  2014           D             2000.0           0.333333
246      43  2014           D                0.0           0.333333
247      45  2014           D                0.0           0.333333
248      46  2014           D                0.0           0.333333
249      47  2014           D                0.0           0.333333

[250 rows x 5 columns]

In [20]:
#missing values for predicotr variable means no vote, which will be classified as against party lines
df_long = df_long.fillna(0)

df_long.isnull().sum()

person               0
Year                 0
party_short          0
donations_dollars    0
partyline_percent    0
dtype: int64

In [21]:
df_long_sorted = df_long.sort_values(by=['person',"Year"])
df_long_sorted.head()

     person  Year party_short  donations_dollars  partyline_percent
0         4  2012           D                0.0           0.000000
224       4  2014           D                0.0           0.333333
448       4  2016           D                0.0           0.400000
672       4  2018           D             1000.0           1.000000
1        10  2012           D                0.0           0.500000

In [22]:
#lag the predictor variable
df_long_sorted['donations_dollars_lag'] = df_long.groupby('person')['donations_dollars'].shift(-1)
df_long_sorted.head(150)

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag
0,4,2012,D,0.0,0.000000,0.0
224,4,2014,D,0.0,0.333333,0.0
448,4,2016,D,0.0,0.400000,1000.0
672,4,2018,D,1000.0,1.000000,NaN
1,10,2012,D,0.0,0.500000,2000.0
...,...,...,...,...,...,...
260,67,2014,D,0.0,0.666667,0.0
484,67,2016,D,0.0,0.600000,0.0
708,67,2018,D,0.0,1.000000,NaN
37,68,2012,D,0.0,0.500000,0.0
261,68,2014,D,0.0,0.333333,0.0

In [23]:
df_long_sorted.head(50)

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag
0,4,2012,D,0.0,0.000000,0.0
224,4,2014,D,0.0,0.333333,0.0
448,4,2016,D,0.0,0.400000,1000.0
672,4,2018,D,1000.0,1.000000,NaN
1,10,2012,D,0.0,0.500000,2000.0
225,10,2014,D,2000.0,0.666667,2000.0
449,10,2016,D,2000.0,0.600000,1000.0
673,10,2018,D,1000.0,1.000000,NaN
2,12,2012,D,0.0,0.250000,0.0
226,12,2014,D,0.0,1.000000,0.0
450,12,2016,D,0.0,0.800000,0.0
674,12,2018,D,0.0,1.000000,NaN
3,14,2012,D,0.0,0.250000,0.0
227,14,2014,D,0.0,0.333333,0.0
451,14,2016,D,0.0,0.400000,3700.0
675,14,2018,D,3700.0,0.000000,NaN
4,15,2012,D,0.0,0.000000,0.0
228,15,2014,D,0.0,0.000000,0.0
452,15,2016,D,0.0,0.200000,0.0
676,15,2018,D,0.0,1.000000,NaN
5,16,2012,D,0.0,0.500000,0.0
229,16,2014,D,0.0,0.333333,0.0
453,16,2016,D,0.0,0.800000,0.0
677,16,2018,D,0.0,1.000000,NaN
6,17,2012,D,0.0,0.000000,0.0
230,17,2014,D,0.0,0.333333,0.0
454,17,2016,D,0.0,0.800000,0.0
678,17,2018,D,0.0,1.000000,NaN
7,18,2012,D,0.0,0.000000,1000.0
231,18,2014,D,1000.0,0.333333,0.0
455,18,2016,D,0.0,0.600000,0.0
679,18,2018,D,0.0,1.000000,NaN
8,19,2012,D,0.0,0.000000,0.0
232,19,2014,D,0.0,0.333333,0.0
456,19,2016,D,0.0,0.800000,80.0
680,19,2018,D,80.0,1.000000,NaN
9,21,2012,D,250.0,0.000000,0.0
233,21,2014,D,0.0,0.333333,0.0
457,21,2016,D,0.0,0.400000,0.0
681,21,2018,D,0.0,1.000000,NaN
10,22,2012,D,0.0,0.500000,0.0
234,22,2014,D,0.0,0.333333,0.0
458,22,2016,D,0.0,0.800000,0.0
682,22,2018,D,0.0,0.000000,NaN
11,23,2012,D,0.0,0.250000,0.0
235,23,2014,D,0.0,0.333333,0.0
459,23,2016,D,0.0,0.400000,0.0
683,23,2018,D,0.0,1.000000,NaN
12,24,2012,D,0.0,0.000000,0.0
236,24,2014,D,0.0,0.333333,0.0

In [24]:
df_long_lagged = df_long_sorted

In [25]:
#df_long.sort_values(by=['person',"Year"])

In [26]:
#create a list of all unique IDs
ids=df_long
data_id=ids.drop_duplicates(subset='person')
data_id=data_id[['person']]
data_id.shape

(224, 1)

In [27]:
#create new variable with random number between one and zero
np.random.seed(42)
data_id['data_use'] = (np.random.randint(0, 10000, data_id.shape[0]))/10000
data_id=data_id[['person', 'data_use']]

In [28]:
#assign each person to a modeling group training or testing with a 50 percent chance 

data_id['MODELING_GROUP'] = np.where(((data_id.data_use <= 0.55)), 'TRAINING', 'TESTING')

In [29]:

groups = data_id.groupby(['MODELING_GROUP'])['person'].count()
groups

MODELING_GROUP
TESTING     108
TRAINING    116
Name: person, dtype: int64

In [30]:
df_long_lagged=df_long_lagged.sort_values(by=['person'], ascending=[True])
data_id=data_id.sort_values(by=['person'], ascending=[True])
df_long_modelgroups_lagged =df_long_lagged.merge(data_id, on=['person'], how='inner')
df_long_modelgroups_lagged.head()

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP
0,4,2012,D,0.0,0.000000,0.0,0.727,TESTING
1,4,2014,D,0.0,0.333333,0.0,0.727,TESTING
2,4,2016,D,0.0,0.400000,1000.0,0.727,TESTING
3,4,2018,D,1000.0,1.000000,NaN,0.727,TESTING
4,10,2012,D,0.0,0.500000,2000.0,0.086,TRAINING

In [31]:
df_long_modelgroups_lagged.head(50)

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP
0,4,2012,D,0.0,0.000000,0.0,0.7270,TESTING
1,4,2014,D,0.0,0.333333,0.0,0.7270,TESTING
2,4,2016,D,0.0,0.400000,1000.0,0.7270,TESTING
3,4,2018,D,1000.0,1.000000,NaN,0.7270,TESTING
4,10,2012,D,0.0,0.500000,2000.0,0.0860,TRAINING
5,10,2014,D,2000.0,0.666667,2000.0,0.0860,TRAINING
6,10,2016,D,2000.0,0.600000,1000.0,0.0860,TRAINING
7,10,2018,D,1000.0,1.000000,NaN,0.0860,TRAINING
8,12,2012,D,0.0,0.250000,0.0,0.5390,TRAINING
9,12,2014,D,0.0,1.000000,0.0,0.5390,TRAINING
10,12,2016,D,0.0,0.800000,0.0,0.5390,TRAINING
11,12,2018,D,0.0,1.000000,NaN,0.5390,TRAINING
12,14,2018,D,3700.0,0.000000,NaN,0.5191,TRAINING
13,14,2016,D,0.0,0.400000,3700.0,0.5191,TRAINING
14,14,2012,D,0.0,0.250000,0.0,0.5191,TRAINING
15,14,2014,D,0.0,0.333333,0.0,0.5191,TRAINING
16,15,2012,D,0.0,0.000000,0.0,0.5734,TESTING
17,15,2014,D,0.0,0.000000,0.0,0.5734,TESTING
18,15,2016,D,0.0,0.200000,0.0,0.5734,TESTING
19,15,2018,D,0.0,1.000000,NaN,0.5734,TESTING
20,16,2018,D,0.0,1.000000,NaN,0.6265,TESTING
21,16,2012,D,0.0,0.500000,0.0,0.6265,TESTING
22,16,2014,D,0.0,0.333333,0.0,0.6265,TESTING
23,16,2016,D,0.0,0.800000,0.0,0.6265,TESTING
24,17,2018,D,0.0,1.000000,NaN,0.0466,TRAINING
25,17,2016,D,0.0,0.800000,0.0,0.0466,TRAINING
26,17,2012,D,0.0,0.000000,0.0,0.0466,TRAINING
27,17,2014,D,0.0,0.333333,0.0,0.0466,TRAINING
28,18,2012,D,0.0,0.000000,1000.0,0.4426,TRAINING
29,18,2014,D,1000.0,0.333333,0.0,0.4426,TRAINING
30,18,2016,D,0.0,0.600000,0.0,0.4426,TRAINING
31,18,2018,D,0.0,1.000000,NaN,0.4426,TRAINING
32,19,2012,D,0.0,0.000000,0.0,0.5578,TESTING
33,19,2014,D,0.0,0.333333,0.0,0.5578,TESTING
34,19,2016,D,0.0,0.800000,80.0,0.5578,TESTING
35,19,2018,D,80.0,1.000000,NaN,0.5578,TESTING
36,21,2018,D,0.0,1.000000,NaN,0.8322,TESTING
37,21,2016,D,0.0,0.400000,0.0,0.8322,TESTING
38,21,2014,D,0.0,0.333333,0.0,0.8322,TESTING
39,21,2012,D,250.0,0.000000,0.0,0.8322,TESTING
40,22,2012,D,0.0,0.500000,0.0,0.1685,TRAINING
41,22,2014,D,0.0,0.333333,0.0,0.1685,TRAINING
42,22,2016,D,0.0,0.800000,0.0,0.1685,TRAINING
43,22,2018,D,0.0,0.000000,NaN,0.1685,TRAINING
44,23,2012,D,0.0,0.250000,0.0,0.0769,TRAINING
45,23,2014,D,0.0,0.333333,0.0,0.0769,TRAINING
46,23,2016,D,0.0,0.400000,0.0,0.0769,TRAINING
47,23,2018,D,0.0,1.000000,NaN,0.0769,TRAINING
48,24,2016,D,0.0,0.800000,0.0,0.6949,TESTING
49,24,2018,D,0.0,1.000000,NaN,0.6949,TESTING

In [32]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [33]:
df_long_modelgroups_lagged['democrat'] = np.where(df_long_modelgroups_lagged['party_short'] == "D", 1, 0)
df_long_modelgroups_lagged.head()

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP,democrat
0,4,2012,D,0.0,0.000000,0.0,0.727,TESTING,1
1,4,2014,D,0.0,0.333333,0.0,0.727,TESTING,1
2,4,2016,D,0.0,0.400000,1000.0,0.727,TESTING,1
3,4,2018,D,1000.0,1.000000,NaN,0.727,TESTING,1
4,10,2012,D,0.0,0.500000,2000.0,0.086,TRAINING,1

In [34]:
!pip install linearmodels

Requirement already satisfied: linearmodels in c:\users\jmitc\anaconda3\lib\site-packages (4.23)
Requirement already satisfied: numpy>=1.16 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.19.1)
Requirement already satisfied: patsy in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.5.1)
Requirement already satisfied: mypy-extensions>=0.4 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.4.3)
Requirement already satisfied: statsmodels>=0.11 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.12.0)
Requirement already satisfied: pandas>=0.24 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.1.3)
Requirement already satisfied: pyhdfe>=0.1 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.1.0)
Requirement already satisfied: property-cached>=1.6.3 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.6.4)
Requirement already satisfied: scipy>=1.2 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.5.0)
Requirement already satisfied: Cython>=0.29.21 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.29.21)
Requirement already satisfied: six in c:\users\jmitc\anaconda3\lib\site-packages (from patsy->linearmodels) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\jmitc\anaconda3\lib\site-packages (from pandas>=0.24->linearmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\jmitc\anaconda3\lib\site-packages (from pandas>=0.24->linearmodels) (2020.1)

In [35]:
from linearmodels import PanelOLS as pols
import statsmodels.api as sm

In [36]:
df_long_modelgroups_lagged["Year"] =  pd.to_datetime(df_long_modelgroups_lagged['Year'], format='%Y')

In [37]:
df_long_modelgroups_lagged = df_long_modelgroups_lagged.set_index(['person', "Year"], drop=True)

In [38]:
df_long_modelgroups_lagged.head()

                  party_short  donations_dollars  partyline_percent  \
person Year
4      2012-01-01           D                0.0           0.000000
       2014-01-01           D                0.0           0.333333
       2016-01-01           D                0.0           0.400000
       2018-01-01           D             1000.0           1.000000
10     2012-01-01           D                0.0           0.500000

                   donations_dollars_lag  data_use MODELING_GROUP  democrat
person Year
4      2012-01-01                    0.0     0.727        TESTING         1
       2014-01-01                    0.0     0.727        TESTING         1
       2016-01-01                 1000.0     0.727        TESTING         1
       2018-01-01                    NaN     0.727        TESTING         1
10     2012-01-01                 2000.0     0.086       TRAINING         1

In [45]:
exog_vars = ["partyline_percent"]

mod = pols(df_long_modelgroups_lagged.donations_dollars_lag,df_long_modelgroups_lagged['partyline_percent'], 
           time_effects = True,entity_effects = True)
pooled_res = mod.fit()
print(pooled_res)

                            PanelOLS Estimation Summary
===================================================================================
Dep. Variable:     donations_dollars_lag   R-squared:                     1.961e-06
Estimator:                      PanelOLS   R-squared (Between):             -0.0027
No. Observations:                    672   R-squared (Within):           -9.305e-05
Date:                   Mon, Mar 29 2021   R-squared (Overall):             -0.0017
Time:                           21:10:57   Log-likelihood                   -5852.0
Cov. Estimator:               Unadjusted
                                           F-statistic:                      0.0009
Entities:                            224   P-value                           0.9764
Avg Obs:                          3.0000   Distribution:                   F(1,445)
Min Obs:                          3.0000
Max Obs:                          3.0000   F-statistic (robust):             0.0009
                                           P-value                           0.9764
Time periods:                          3   Distribution:                   F(1,445)
Avg Obs:                          224.00
Min Obs:                          224.00
Max Obs:                          224.00

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
partyline_percent    -13.553     458.77    -0.0295     0.9764     -915.17      888.07
=====================================================================================

F-test for Poolability: 2.7117
P-value: 0.0000
Distribution: F(225,445)

Included effects: Entity, Time

In [48]:
test = mod.predict(train_df[exog_vars], data=df_long_modelgroups_lagged, exog=None)

ValueError: Unable to use data when the model was not created using a formula.

In [49]:
df_long_modelgroups_lagged.to_csv(r'C:\Users\jmitc\rollcall\walt_disney_PANELMODEL.csv',index = True)

In [41]:
train_df = df_long_modelgroups_lagged[df_long_modelgroups_lagged.MODELING_GROUP=="TRAINING"]
test_df = df_long_modelgroups_lagged[df_long_modelgroups_lagged.MODELING_GROUP=="TESTING"]

In [42]:
train_model = pols(train_df['donations_dollars_lag'],train_df[exog_vars], entity_effects = True, 
                   time_effects = True)
train_fit_vals = train_model.fit()

In [43]:
train_fit_vals

                            PanelOLS Estimation Summary
===================================================================================
Dep. Variable:     donations_dollars_lag   R-squared:                        0.0005
Estimator:                      PanelOLS   R-squared (Between):             -0.0462
No. Observations:                    348   R-squared (Within):               0.0005
Date:                   Mon, Mar 29 2021   R-squared (Overall):             -0.0298
Time:                           21:08:25   Log-likelihood                   -2959.1
Cov. Estimator:               Unadjusted
                                           F-statistic:                      0.1200
Entities:                            116   P-value                           0.7293
Avg Obs:                          3.0000   Distribution:                   F(1,229)
Min Obs:                          3.0000
Max Obs:                          3.0000   F-statistic (robust):             0.1200
                                           P-value                           0.7293
Time periods:                          3   Distribution:                   F(1,229)
Avg Obs:                          116.00
Min Obs:                          116.00
Max Obs:                          116.00

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
partyline_percent    -177.52     512.40    -0.3465     0.7293     -1187.2      832.11
=====================================================================================

F-test for Poolability: 3.0404
P-value: 0.0000
Distribution: F(117,229)

Included effects: Entity, Time
PanelEffectsResults, id: 0x1e205cd6b50

In [44]:
train_predictions = train_model.predict(train_df[exog_vars])

AssertionError: