In [15]:

import csv
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

,person_x,name,VoteAlong113thRatio_FS_IIR,VoteAlong114thRatio_FS_IIR,VoteAlong115thRatio_FS_IIR,VoteAlong116thRatio_FS_IIR,VoteAlong113thRatio_FS_FSS,VoteAlong114thRatio_FS_FSS,VoteAlong115thRatio_FS_FSS,VoteAlong116thRatio_FS_FSS,...,disney_donations2012,disney_donations2014,disney_donations2016,disney_donations2018,person_y,party_y,VoteAlong113thRatio_Film,VoteAlong114thRatio_Film,VoteAlong115thRatio_Film,VoteAlong116thRatio_Film
0,400008,"Rep. Robert “Rob” Andrews [D, 1990-2014]",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,400008.0,NaN,NaN,NaN,NaN,NaN
1,400021,"Rep. Xavier Becerra [D, 2013-2017]",0.333333,0.6,NaN,NaN,0.333333,0.000000,NaN,NaN,...,NaN,NaN,NaN,NaN,400021.0,Democrat,0.00,0.666667,NaN,NaN
2,400030,"Rep. Sanford Bishop Jr. [D, 1993-2022]",0.500000,0.8,0.428571,1.0,0.666667,0.333333,0.555556,1.0,...,NaN,NaN,NaN,NaN,400030.0,Democrat,0.75,0.333333,0.6,1.0
3,400031,"Rep. Timothy Bishop [D, 2003-2014]",0.500000,NaN,NaN,NaN,0.666667,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,400031.0,Democrat,0.50,NaN,NaN,NaN
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",0.333333,0.8,0.428571,1.0,0.333333,0.333333,0.222222,1.0,...,0.0,0.0,0.0,1000.0,400033.0,Democrat,0.00,0.333333,0.4,1.0

In [ ]:
#Load DataSet that contains all MoH and the Disney Donation Data

xx = "~/Documents/GitHub/CampaignDonations/Output_Data/MoH_Vote_Data.csv"

df = pd.read_csv(xx)

df.head()

In [16]:
df.columns.tolist()

['person_x',
 'name',
 'VoteAlong113thRatio_FS_IIR',
 'VoteAlong114thRatio_FS_IIR',
 'VoteAlong115thRatio_FS_IIR',
 'VoteAlong116thRatio_FS_IIR',
 'VoteAlong113thRatio_FS_FSS',
 'VoteAlong114thRatio_FS_FSS',
 'VoteAlong115thRatio_FS_FSS',
 'VoteAlong116thRatio_FS_FSS',
 'VoteAlong113thRatio_FS_CM',
 'VoteAlong114thRatio_FS_CM',
 'VoteAlong115thRatio_FS_CM',
 'VoteAlong116thRatio_FS_CM',
 'VoteAlong113thRatio_FS_REB',
 'VoteAlong114thRatio_FS_REB',
 'VoteAlong115thRatio_FS_REB',
 'VoteAlong116thRatio_FS_REB',
 'party_short',
 'Pure_name',
 'LastName',
 'FirstName',
 'ID_NameParty',
 'first',
 'last',
 'party_x',
 'pageid',
 'wikidataid',
 'wikititle',
 'name_y',
 'sex',
 'ethnicity',
 'religion',
 'birth',
 'death',
 'birthplace',
 'deathplace',
 'Number_Sessions_Served',
 'Session_113',
 'Session_114',
 'Session_115',
 'Session_116',
 'disney_donations2012',
 'disney_donations2014',
 'disney_donations2016',
 'disney_donations2018',
 'person_y',
 'party_y',
 'VoteAlong113thRatio_Film',
 'VoteAlong114thRatio_Film',
 'VoteAlong115thRatio_Film',
 'VoteAlong116thRatio_Film']

In [17]:
# Only keep MoHs that served in all 4 sessions 
df.drop(df[df.Number_Sessions_Served != 4.0].index, inplace=True)
recode = ['disney_donations2012', 'disney_donations2014', 'disney_donations2016','disney_donations2018']
df[recode] = df[recode].fillna(0)

In [18]:
df.head()

,person_x,name,VoteAlong113thRatio_FS_IIR,VoteAlong114thRatio_FS_IIR,VoteAlong115thRatio_FS_IIR,VoteAlong116thRatio_FS_IIR,VoteAlong113thRatio_FS_FSS,VoteAlong114thRatio_FS_FSS,VoteAlong115thRatio_FS_FSS,VoteAlong116thRatio_FS_FSS,...,disney_donations2012,disney_donations2014,disney_donations2016,disney_donations2018,person_y,party_y,VoteAlong113thRatio_Film,VoteAlong114thRatio_Film,VoteAlong115thRatio_Film,VoteAlong116thRatio_Film
4,400033,"Rep. Earl Blumenauer [D, 1996-2022]",0.333333,0.8,0.428571,1.0,0.333333,0.333333,0.222222,1.000000,...,0.0,0.0,0.0,1000.0,400033.0,Democrat,0.00,0.333333,0.4,1.0
10,400075,"Rep. James “Jim” Clyburn [D, 1993-2022]",0.500000,0.8,0.285714,1.0,0.666667,0.333333,0.444444,1.000000,...,0.0,2000.0,2000.0,1000.0,400075.0,Democrat,0.50,0.666667,0.6,1.0
13,400081,"Rep. Jim Cooper [D, 2003-2022]",0.500000,0.8,0.428571,1.0,0.666667,0.333333,0.555556,0.666667,...,0.0,0.0,0.0,0.0,400081.0,Democrat,0.25,1.000000,0.8,1.0
15,400090,"Rep. Elijah Cummings [D, 1996-2019]",0.333333,0.8,0.142857,NaN,0.333333,0.333333,0.333333,1.000000,...,0.0,0.0,0.0,3700.0,400090.0,Democrat,0.25,0.333333,0.4,NaN
16,400090,"Rep. Elijah Cummings [D, 1996-2019]",0.333333,0.8,0.142857,NaN,0.333333,0.333333,0.333333,1.000000,...,0.0,0.0,0.0,3700.0,400090.0,NaN,NaN,NaN,NaN,NaN

In [19]:
# recode_sessions = ["lcycle1", ["lcycle2"], ['lcycle3'],["lcycle4"]]
# recode_donations = ["dcycle1", "dcycle2", 'dcycle3'],["dcycle4"]]
# old_donor_columns = [['donations2012'], ['donations2014'], ['donations2016'],['donations2018']]
# df[recode_donations] = df[old_donor_columns]

df.rename(columns = {'disney_donations2012': "d2012", "disney_donations2014": "d2014", "disney_donations2016":"d2016", "disney_donations2018":"d2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_Film': "f2012", "VoteAlong114thRatio_Film": "f2014", "VoteAlong115thRatio_Film":"f2016", "VoteAlong116thRatio_Film":"f2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_IIR': "i2012", "VoteAlong114thRatio_FS_IIR": "i2014", "VoteAlong115thRatio_FS_IIR":"i2016", "VoteAlong116thRatio_FS_IIR":"i2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_FSS': "s2012", "VoteAlong114thRatio_FS_FSS": "s2014", "VoteAlong115thRatio_FS_FSS":"s2016", "VoteAlong116thRatio_FS_FSS":"s2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_CM': "c2012", "VoteAlong114thRatio_FS_CM": "c2014", "VoteAlong115thRatio_FS_CM":"c2016", "VoteAlong116thRatio_FS_CM":"c2018"}, inplace = True)

df.rename(columns = {'VoteAlong113thRatio_FS_REB': "r2012", "VoteAlong114thRatio_FS_REB": "r2014", "VoteAlong115thRatio_FS_REB":"r2016", "VoteAlong116thRatio_FS_REB":"r2018"}, inplace = True)

In [20]:
df.dtypes

person_x                    int64
name                       object
i2012                     float64
i2014                     float64
i2016                     float64
i2018                     float64
s2012                     float64
s2014                     float64
s2016                     float64
s2018                     float64
c2012                     float64
c2014                     float64
c2016                     float64
c2018                     float64
r2012                     float64
r2014                     float64
r2016                     float64
r2018                     float64
party_short                object
Pure_name                  object
LastName                   object
FirstName                  object
ID_NameParty               object
first                      object
last                       object
party_x                    object
pageid                    float64
wikidataid                 object
wikititle                  object
name_y                     object
sex                        object
ethnicity                  object
religion                   object
birth                      object
death                     float64
birthplace                 object
deathplace                float64
Number_Sessions_Served    float64
Session_113                object
Session_114                object
Session_115                object
Session_116                object
d2012                     float64
d2014                     float64
d2016                     float64
d2018                     float64
person_y                  float64
party_y                    object
f2012                     float64
f2014                     float64
f2016                     float64
f2018                     float64
dtype: object

In [12]:
df_forlong = df[['person',
                "l2012", "l2014",'l2016',"l2018",
                "d2012", "d2014",'d2016',"d2018",
                "party_short"]].copy()

In [13]:
df_forlong.head()

,person,l2012,l2014,l2016,l2018,d2012,d2014,d2016,d2018,party_short
4,400033,0.00,0.333333,0.4,1.0,0.0,0.0,0.0,1000.0,D
10,400075,0.50,0.666667,0.6,1.0,0.0,2000.0,2000.0,1000.0,D
12,400081,0.25,1.000000,0.8,1.0,0.0,0.0,0.0,0.0,D
14,400090,0.25,0.333333,0.4,NaN,0.0,0.0,0.0,3700.0,D
15,400093,0.00,0.000000,0.2,1.0,0.0,0.0,0.0,0.0,D

In [21]:
df["person"] = df.index
df_long = pd.wide_to_long(df, ["d", "f", "i", "s", "c", "r"], i="person", j="Year")

df_long.rename(columns = {'d':"disney_donations", "f":"VoteAlongRatio_Film", "i":"VoteAlongRatio_FS_IIR", "s":"VoteAlongRatio_FS_FSS", "c":"VoteAlongRatio_FS_CM", "r":"VoteAlongRatio_FS_REB", }, inplace = True)

In [22]:
df_long.head(30)

,,wikidataid,sex,last,person_y,FirstName,first,death,Number_Sessions_Served,party_short,person_x,...,Pure_name,name_y,religion,birthplace,disney_donations,VoteAlongRatio_Film,VoteAlongRatio_FS_IIR,VoteAlongRatio_FS_FSS,VoteAlongRatio_FS_CM,VoteAlongRatio_FS_REB
person,Year,,,,,,,,,,,,,,,,,,,,,
4,2012,Q748066,male,Blumenauer,400033.0,Earl,Earl,NaN,4.0,D,400033,...,Earl Blumenauer,Earl Blumenauer,NaN,"45.51667,-122.66667",0.0,0.00,0.333333,0.333333,0.571429,0.666667
10,2012,Q1289889,male,Clyburn,400075.0,James,James,NaN,4.0,D,400075,...,James “Jim” Clyburn,James E. Clyburn,protestantism methodist,"33.92056,-80.34472",0.0,0.50,0.500000,0.666667,0.571429,0.666667
13,2012,Q973737,male,Cooper,400081.0,Jim,Jim,NaN,4.0,D,400081,...,Jim Cooper,Jim Cooper,anglicanism,"36.165,-86.78389",0.0,0.25,0.500000,0.666667,0.714286,0.666667
15,2012,Q934898,male,Cummings,400090.0,Elijah,Elijah,NaN,4.0,D,400090,...,Elijah Cummings,Elijah Cummings,protestantism baptist,"39.28639,-76.615",0.0,0.25,0.333333,0.333333,0.571429,0.666667
16,2012,Q934898,male,Cummings,400090.0,Elijah,Elijah,NaN,4.0,D,400090,...,Elijah Cummings,Elijah Cummings,protestantism baptist,"39.28639,-76.615",0.0,NaN,0.333333,0.333333,0.571429,0.666667
17,2012,Q1164657,male,Davis,400093.0,Danny,Danny,NaN,4.0,D,400093,...,Danny Davis,Danny K. Davis,protestantism baptist,"33.12167,-91.5475",0.0,0.00,0.166667,0.333333,0.571429,0.666667
18,2012,Q460675,female,Davis,400097.0,Susan,Susan,NaN,4.0,D,400097,...,Susan Davis,Susan Davis,judaism,"42.375,-71.10611",0.0,0.50,0.333333,0.666667,0.714286,0.666667
19,2012,Q1758507,male,DeFazio,400100.0,Peter,Peter,NaN,4.0,D,400100,...,Peter DeFazio,Peter A. DeFazio,catholicism,"42.28333,-71.23333",0.0,0.00,0.333333,0.333333,0.571429,0.666667
20,2012,Q437159,female,DeGette,400101.0,Diana,Diana,NaN,4.0,D,400101,...,Diana DeGette,Diana DeGette,protestantism reformed,"35.69389,139.41944",0.0,0.00,0.500000,0.333333,0.714286,0.666667
21,2012,Q434952,female,DeLauro,400103.0,Rosa,Rosa,NaN,4.0,D,400103,...,Rosa DeLauro,Rosa L. DeLauro,catholicism,"41.30833,-72.925",0.0,0.00,0.333333,0.333333,0.571429,0.333333
23,2012,Q363817,male,Doggett,400111.0,Lloyd,Lloyd,NaN,4.0,D,400111,...,Lloyd Doggett,Lloyd Doggett,protestantism methodist,"30.3,-97.73333",250.0,0.00,0.333333,0.333333,0.571429,0.666667
24,2012,Q1344200,male,Doyle,400114.0,Michael,Michael,NaN,4.0,D,400114,...,Michael Doyle,Michael F. Doyle,catholicism,"40.42222,-79.88611",0.0,0.50,0.500000,0.333333,0.571429,1.000000
25,2012,Q1329618,male,Engel,400122.0,Eliot,Eliot,NaN,4.0,D,400122,...,Eliot Engel,Eliot L. Engel,judaism,"40.67,-73.94",0.0,0.25,0.500000,0.333333,0.714286,0.666667
26,2012,Q291193,female,Eshoo,400124.0,Anna,Anna,NaN,4.0,D,400124,...,Anna Eshoo,Anna G. Eshoo,catholicism,"41.675,-72.78722",0.0,0.00,0.500000,0.333333,0.714286,0.666667
30,2012,Q946606,male,Grijalva,400162.0,Raúl,Raúl,NaN,4.0,D,400162,...,Raúl Grijalva,Raúl M. Grijalva,catholicism,"32.22167,-110.92639",0.0,0.00,0.333333,0.000000,0.571429,0.666667
32,2012,Q1758631,male,Hastings,NaN,Alcee,Alcee,NaN,4.0,D,400170,...,Alcee Hastings,Alcee L. Hastings,protestantism methodist,"28.66139,-81.39194",0.0,NaN,0.333333,0.333333,0.571429,0.666667
36,2012,Q516515,male,Hoyer,400189.0,Steny,Steny,NaN,4.0,D,400189,...,Steny Hoyer,Steny H. Hoyer,protestantism baptist,"40.67,-73.94",4675.0,0.50,0.500000,0.666667,0.714286,0.666667
39,2012,Q461526,female,Johnson,400204.0,Eddie,Eddie,NaN,4.0,D,400204,...,Eddie Johnson,Eddie Bernice Johnson,protestantism baptist,"31.55139,-97.15583",0.0,0.25,0.333333,0.333333,0.428571,0.666667
40,2012,Q436537,female,Kaptur,400211.0,Marcy,Marcy,NaN,4.0,D,400211,...,Marcy Kaptur,Marcy Kaptur,catholicism,"41.66667,-83.58333",0.0,0.50,0.333333,0.666667,0.571429,0.666667
41,2012,Q505222,male,Kind,400218.0,Ron,Ron,NaN,4.0,D,400218,...,Ron Kind,Ron Kind,protestantism lutheran,"43.81333,-91.23306",0.0,0.50,0.500000,0.333333,0.714286,0.333333
42,2012,Q1397290,male,Langevin,400230.0,James,James,NaN,4.0,D,400230,...,James “Jim” Langevin,James Langevin,catholicism,"41.83083,-71.415",0.0,0.25,0.333333,0.333333,0.714286,0.666667
43,2012,Q503529,male,Larsen,400232.0,Rick,Rick,NaN,4.0,D,400232,...,Rick Larsen,Rick Larsen,protestantism methodist,"48.1811,-122.139",0.0,0.25,0.500000,0.333333,0.714286,0.666667
44,2012,Q357832,male,Larson,400233.0,John,John,NaN,4.0,D,400233,...,John Larson,John Larson,catholicism,"41.76333,-72.685",2000.0,0.25,0.333333,0.333333,0.571429,0.333333
45,2012,Q289317,female,Lee,400237.0,Barbara,Barbara,NaN,4.0,D,400237,...,Barbara Lee,Barbara Lee,protestantism baptist,"31.79028,-106.42333",0.0,0.00,0.333333,0.000000,0.571429,0.666667
47,2012,Q45380,male,Lewis,400240.0,John,John,NaN,4.0,D,400240,...,John Lewis,John Lewis,protestantism baptist,"31.80196,-85.96732",0.0,0.00,0.333333,0.333333,0.571429,0.666667
48,2012,Q218217,female,Lofgren,400245.0,Zoe,Zoe,NaN,4.0,D,400245,...,Zoe Lofgren,Zoe Lofgren,protestantism lutheran,"37.55417,-122.31306",0.0,0.00,0.333333,0.333333,0.285714,0.666667
49,2012,Q460652,female,Lowey,400246.0,Nita,Nita,NaN,4.0,D,400246,...,Nita Lowey,Nita M. Lowey,judaism,"40.67,-73.94",0.0,0.50,0.500000,0.666667,0.714286,0.666667
50,2012,Q2344921,male,Lynch,400249.0,Stephen,Stephen,NaN,4.0,D,400249,...,Stephen Lynch,Stephen Lynch,catholicism,"42.35778,-71.06167",0.0,0.25,0.500000,0.333333,0.571429,1.000000
51,2012,Q455833,female,Maloney,400251.0,Carolyn,Carolyn,NaN,4.0,D,400251,...,Carolyn Maloney,Carolyn B. Maloney,protestantism reformed,"36.08,-79.81944",0.0,0.25,0.500000,0.000000,0.714286,0.666667
54,2012,Q434893,female,McCollum,400259.0,Betty,Betty,NaN,4.0,D,400259,...,Betty McCollum,Betty McCollum,catholicism,"44.9733,-93.2643",0.0,0.00,0.333333,0.333333,0.714286,0.666667

In [14]:
df_forlong["person"] = df.index
df_long = pd.wide_to_long(df_forlong, ["d", "f", "i", "s", "c", "r"], i="person", j="Year")

df_long.rename(columns = {'d':"disney_donations", "f":"VoteAlongRatio_Film", "i":"VoteAlongRatio_FS_IIR", "s":"VoteAlongRatio_FS_FSS", "c":"VoteAlongRatio_FS_CM", "r":"VoteAlongRatio_FS_REB", }, inplace = True)

In [27]:
df_long.reset_index(inplace=True)

#missing values for predicotr variable means no vote, which will be classified as against party lines
df_long = df_long.fillna(0)

#  df_long.isnull().sum()

In [32]:
df_long_sorted = df_long.sort_values(by=['person',"Year"])
df_long_sorted.head()

,level_0,index,person,Year,wikidataid,sex,last,person_y,FirstName,first,...,Pure_name,name_y,religion,birthplace,disney_donations,VoteAlongRatio_Film,VoteAlongRatio_FS_IIR,VoteAlongRatio_FS_FSS,VoteAlongRatio_FS_CM,VoteAlongRatio_FS_REB
0,0,0,4,2012,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,Earl Blumenauer,Earl Blumenauer,0,"45.51667,-122.66667",0.0,0.000000,0.333333,0.333333,0.571429,0.666667
229,229,229,4,2014,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,Earl Blumenauer,Earl Blumenauer,0,"45.51667,-122.66667",0.0,0.333333,0.800000,0.333333,0.400000,0.500000
458,458,458,4,2016,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,Earl Blumenauer,Earl Blumenauer,0,"45.51667,-122.66667",0.0,0.400000,0.428571,0.222222,0.000000,0.000000
687,687,687,4,2018,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,Earl Blumenauer,Earl Blumenauer,0,"45.51667,-122.66667",1000.0,1.000000,1.000000,1.000000,1.000000,1.000000
1,1,1,10,2012,Q1289889,male,Clyburn,400075.0,James,James,...,James “Jim” Clyburn,James E. Clyburn,protestantism methodist,"33.92056,-80.34472",0.0,0.500000,0.500000,0.666667,0.571429,0.666667

In [33]:
#lag the predictor variable
df_long_sorted['disney_donations_lagMinus1'] = df_long.groupby('person')['disney_donations'].shift(-1)
df_long_sorted['disney_donations_lagPlus1'] = df_long.groupby('person')['disney_donations'].shift(+1)
df_long_sorted.head(150)

,level_0,index,person,Year,wikidataid,sex,last,person_y,FirstName,first,...,religion,birthplace,disney_donations,VoteAlongRatio_Film,VoteAlongRatio_FS_IIR,VoteAlongRatio_FS_FSS,VoteAlongRatio_FS_CM,VoteAlongRatio_FS_REB,disney_donations_lagMinus1,disney_donations_lagPlus1
0,0,0,4,2012,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,0,"45.51667,-122.66667",0.0,0.000000,0.333333,0.333333,0.571429,0.666667,0.0,NaN
229,229,229,4,2014,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,0,"45.51667,-122.66667",0.0,0.333333,0.800000,0.333333,0.400000,0.500000,0.0,0.0
458,458,458,4,2016,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,0,"45.51667,-122.66667",0.0,0.400000,0.428571,0.222222,0.000000,0.000000,1000.0,0.0
687,687,687,4,2018,Q748066,male,Blumenauer,400033.0,Earl,Earl,...,0,"45.51667,-122.66667",1000.0,1.000000,1.000000,1.000000,1.000000,1.000000,NaN,0.0
1,1,1,10,2012,Q1289889,male,Clyburn,400075.0,James,James,...,protestantism methodist,"33.92056,-80.34472",0.0,0.500000,0.500000,0.666667,0.571429,0.666667,2000.0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
265,265,265,68,2014,Q170581,female,Pelosi,400314.0,Nancy,Nancy,...,catholicism,"39.28639,-76.615",2600.0,0.333333,0.800000,0.333333,0.400000,0.250000,2610.0,0.0
494,494,494,68,2016,Q170581,female,Pelosi,400314.0,Nancy,Nancy,...,catholicism,"39.28639,-76.615",2610.0,0.600000,0.142857,0.333333,0.000000,0.000000,1602.0,2600.0
723,723,723,68,2018,Q170581,female,Pelosi,400314.0,Nancy,Nancy,...,catholicism,"39.28639,-76.615",1602.0,1.000000,0.000000,0.000000,1.000000,0.000000,NaN,2610.0
37,37,37,69,2012,Q434458,male,Peterson,400316.0,Collin,Collin,...,protestantism lutheran,"46.87722,-96.78944",0.0,0.500000,0.833333,0.333333,0.714286,0.666667,0.0,NaN
266,266,266,69,2014,Q434458,male,Peterson,400316.0,Collin,Collin,...,protestantism lutheran,"46.87722,-96.78944",0.0,0.666667,1.000000,0.333333,0.600000,1.000000,0.0,0.0

In [34]:
MoH_Vote_Data_Long_Sorted = df_long_sorted

In [35]:
# Save Data-Set externally

compression_opts = dict(method='zip',
                        archive_name='MoH_Vote_Data_Long_Sorted.csv')  
MoH_Vote_Data_Long_Sorted.to_csv('MoH_Vote_Data_Long_Sorted.zip', index=False,
          compression=compression_opts)

In [26]:
#create a list of all unique IDs
ids=df_long
data_id=ids.drop_duplicates(subset='person')
data_id=data_id[['person']]
data_id.shape

(224, 1)

In [27]:
#create new variable with random number between one and zero
np.random.seed(42)
data_id['data_use'] = (np.random.randint(0, 10000, data_id.shape[0]))/10000
data_id=data_id[['person', 'data_use']]

In [28]:
#assign each person to a modeling group training or testing with a 50 percent chance 

data_id['MODELING_GROUP'] = np.where(((data_id.data_use <= 0.55)), 'TRAINING', 'TESTING')

In [29]:

groups = data_id.groupby(['MODELING_GROUP'])['person'].count()
groups

MODELING_GROUP
TESTING     108
TRAINING    116
Name: person, dtype: int64

In [30]:
df_long_lagged=df_long_lagged.sort_values(by=['person'], ascending=[True])
data_id=data_id.sort_values(by=['person'], ascending=[True])
df_long_modelgroups_lagged =df_long_lagged.merge(data_id, on=['person'], how='inner')
df_long_modelgroups_lagged.head()

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP
0,4,2012,D,0.0,0.000000,0.0,0.727,TESTING
1,4,2014,D,0.0,0.333333,0.0,0.727,TESTING
2,4,2016,D,0.0,0.400000,1000.0,0.727,TESTING
3,4,2018,D,1000.0,1.000000,NaN,0.727,TESTING
4,10,2012,D,0.0,0.500000,2000.0,0.086,TRAINING

In [31]:
df_long_modelgroups_lagged.head(50)

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP
0,4,2012,D,0.0,0.000000,0.0,0.7270,TESTING
1,4,2014,D,0.0,0.333333,0.0,0.7270,TESTING
2,4,2016,D,0.0,0.400000,1000.0,0.7270,TESTING
3,4,2018,D,1000.0,1.000000,NaN,0.7270,TESTING
4,10,2012,D,0.0,0.500000,2000.0,0.0860,TRAINING
5,10,2014,D,2000.0,0.666667,2000.0,0.0860,TRAINING
6,10,2016,D,2000.0,0.600000,1000.0,0.0860,TRAINING
7,10,2018,D,1000.0,1.000000,NaN,0.0860,TRAINING
8,12,2012,D,0.0,0.250000,0.0,0.5390,TRAINING
9,12,2014,D,0.0,1.000000,0.0,0.5390,TRAINING
10,12,2016,D,0.0,0.800000,0.0,0.5390,TRAINING
11,12,2018,D,0.0,1.000000,NaN,0.5390,TRAINING
12,14,2018,D,3700.0,0.000000,NaN,0.5191,TRAINING
13,14,2016,D,0.0,0.400000,3700.0,0.5191,TRAINING
14,14,2012,D,0.0,0.250000,0.0,0.5191,TRAINING
15,14,2014,D,0.0,0.333333,0.0,0.5191,TRAINING
16,15,2012,D,0.0,0.000000,0.0,0.5734,TESTING
17,15,2014,D,0.0,0.000000,0.0,0.5734,TESTING
18,15,2016,D,0.0,0.200000,0.0,0.5734,TESTING
19,15,2018,D,0.0,1.000000,NaN,0.5734,TESTING
20,16,2018,D,0.0,1.000000,NaN,0.6265,TESTING
21,16,2012,D,0.0,0.500000,0.0,0.6265,TESTING
22,16,2014,D,0.0,0.333333,0.0,0.6265,TESTING
23,16,2016,D,0.0,0.800000,0.0,0.6265,TESTING
24,17,2018,D,0.0,1.000000,NaN,0.0466,TRAINING
25,17,2016,D,0.0,0.800000,0.0,0.0466,TRAINING
26,17,2012,D,0.0,0.000000,0.0,0.0466,TRAINING
27,17,2014,D,0.0,0.333333,0.0,0.0466,TRAINING
28,18,2012,D,0.0,0.000000,1000.0,0.4426,TRAINING
29,18,2014,D,1000.0,0.333333,0.0,0.4426,TRAINING
30,18,2016,D,0.0,0.600000,0.0,0.4426,TRAINING
31,18,2018,D,0.0,1.000000,NaN,0.4426,TRAINING
32,19,2012,D,0.0,0.000000,0.0,0.5578,TESTING
33,19,2014,D,0.0,0.333333,0.0,0.5578,TESTING
34,19,2016,D,0.0,0.800000,80.0,0.5578,TESTING
35,19,2018,D,80.0,1.000000,NaN,0.5578,TESTING
36,21,2018,D,0.0,1.000000,NaN,0.8322,TESTING
37,21,2016,D,0.0,0.400000,0.0,0.8322,TESTING
38,21,2014,D,0.0,0.333333,0.0,0.8322,TESTING
39,21,2012,D,250.0,0.000000,0.0,0.8322,TESTING
40,22,2012,D,0.0,0.500000,0.0,0.1685,TRAINING
41,22,2014,D,0.0,0.333333,0.0,0.1685,TRAINING
42,22,2016,D,0.0,0.800000,0.0,0.1685,TRAINING
43,22,2018,D,0.0,0.000000,NaN,0.1685,TRAINING
44,23,2012,D,0.0,0.250000,0.0,0.0769,TRAINING
45,23,2014,D,0.0,0.333333,0.0,0.0769,TRAINING
46,23,2016,D,0.0,0.400000,0.0,0.0769,TRAINING
47,23,2018,D,0.0,1.000000,NaN,0.0769,TRAINING
48,24,2016,D,0.0,0.800000,0.0,0.6949,TESTING
49,24,2018,D,0.0,1.000000,NaN,0.6949,TESTING

In [32]:
from sklearn.linear_model import LinearRegression
lr = LinearRegression()

In [33]:
df_long_modelgroups_lagged['democrat'] = np.where(df_long_modelgroups_lagged['party_short'] == "D", 1, 0)
df_long_modelgroups_lagged.head()

,person,Year,party_short,donations_dollars,partyline_percent,donations_dollars_lag,data_use,MODELING_GROUP,democrat
0,4,2012,D,0.0,0.000000,0.0,0.727,TESTING,1
1,4,2014,D,0.0,0.333333,0.0,0.727,TESTING,1
2,4,2016,D,0.0,0.400000,1000.0,0.727,TESTING,1
3,4,2018,D,1000.0,1.000000,NaN,0.727,TESTING,1
4,10,2012,D,0.0,0.500000,2000.0,0.086,TRAINING,1

In [34]:
!pip install linearmodels

Requirement already satisfied: linearmodels in c:\users\jmitc\anaconda3\lib\site-packages (4.23)
Requirement already satisfied: numpy>=1.16 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.19.1)
Requirement already satisfied: patsy in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.5.1)
Requirement already satisfied: mypy-extensions>=0.4 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.4.3)
Requirement already satisfied: statsmodels>=0.11 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.12.0)
Requirement already satisfied: pandas>=0.24 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.1.3)
Requirement already satisfied: pyhdfe>=0.1 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.1.0)
Requirement already satisfied: property-cached>=1.6.3 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.6.4)
Requirement already satisfied: scipy>=1.2 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (1.5.0)
Requirement already satisfied: Cython>=0.29.21 in c:\users\jmitc\anaconda3\lib\site-packages (from linearmodels) (0.29.21)
Requirement already satisfied: six in c:\users\jmitc\anaconda3\lib\site-packages (from patsy->linearmodels) (1.15.0)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\jmitc\anaconda3\lib\site-packages (from pandas>=0.24->linearmodels) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in c:\users\jmitc\anaconda3\lib\site-packages (from pandas>=0.24->linearmodels) (2020.1)

In [35]:
from linearmodels import PanelOLS as pols
import statsmodels.api as sm

In [36]:
df_long_modelgroups_lagged["Year"] =  pd.to_datetime(df_long_modelgroups_lagged['Year'], format='%Y')

In [37]:
df_long_modelgroups_lagged = df_long_modelgroups_lagged.set_index(['person', "Year"], drop=True)

In [38]:
df_long_modelgroups_lagged.head()

                  party_short  donations_dollars  partyline_percent  \
person Year
4      2012-01-01           D                0.0           0.000000
       2014-01-01           D                0.0           0.333333
       2016-01-01           D                0.0           0.400000
       2018-01-01           D             1000.0           1.000000
10     2012-01-01           D                0.0           0.500000

                   donations_dollars_lag  data_use MODELING_GROUP  democrat
person Year
4      2012-01-01                    0.0     0.727        TESTING         1
       2014-01-01                    0.0     0.727        TESTING         1
       2016-01-01                 1000.0     0.727        TESTING         1
       2018-01-01                    NaN     0.727        TESTING         1
10     2012-01-01                 2000.0     0.086       TRAINING         1

In [45]:
exog_vars = ["partyline_percent"]

mod = pols(df_long_modelgroups_lagged.donations_dollars_lag,df_long_modelgroups_lagged['partyline_percent'], 
           time_effects = True,entity_effects = True)
pooled_res = mod.fit()
print(pooled_res)

                            PanelOLS Estimation Summary
===================================================================================
Dep. Variable:     donations_dollars_lag   R-squared:                     1.961e-06
Estimator:                      PanelOLS   R-squared (Between):             -0.0027
No. Observations:                    672   R-squared (Within):           -9.305e-05
Date:                   Mon, Mar 29 2021   R-squared (Overall):             -0.0017
Time:                           21:10:57   Log-likelihood                   -5852.0
Cov. Estimator:               Unadjusted
                                           F-statistic:                      0.0009
Entities:                            224   P-value                           0.9764
Avg Obs:                          3.0000   Distribution:                   F(1,445)
Min Obs:                          3.0000
Max Obs:                          3.0000   F-statistic (robust):             0.0009
                                           P-value                           0.9764
Time periods:                          3   Distribution:                   F(1,445)
Avg Obs:                          224.00
Min Obs:                          224.00
Max Obs:                          224.00

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
partyline_percent    -13.553     458.77    -0.0295     0.9764     -915.17      888.07
=====================================================================================

F-test for Poolability: 2.7117
P-value: 0.0000
Distribution: F(225,445)

Included effects: Entity, Time

In [48]:
test = mod.predict(train_df[exog_vars], data=df_long_modelgroups_lagged, exog=None)

ValueError: Unable to use data when the model was not created using a formula.

In [49]:
df_long_modelgroups_lagged.to_csv(r'C:\Users\jmitc\rollcall\walt_disney_PANELMODEL.csv',index = True)

In [41]:
train_df = df_long_modelgroups_lagged[df_long_modelgroups_lagged.MODELING_GROUP=="TRAINING"]
test_df = df_long_modelgroups_lagged[df_long_modelgroups_lagged.MODELING_GROUP=="TESTING"]

In [42]:
train_model = pols(train_df['donations_dollars_lag'],train_df[exog_vars], entity_effects = True, 
                   time_effects = True)
train_fit_vals = train_model.fit()

In [43]:
train_fit_vals

                            PanelOLS Estimation Summary
===================================================================================
Dep. Variable:     donations_dollars_lag   R-squared:                        0.0005
Estimator:                      PanelOLS   R-squared (Between):             -0.0462
No. Observations:                    348   R-squared (Within):               0.0005
Date:                   Mon, Mar 29 2021   R-squared (Overall):             -0.0298
Time:                           21:08:25   Log-likelihood                   -2959.1
Cov. Estimator:               Unadjusted
                                           F-statistic:                      0.1200
Entities:                            116   P-value                           0.7293
Avg Obs:                          3.0000   Distribution:                   F(1,229)
Min Obs:                          3.0000
Max Obs:                          3.0000   F-statistic (robust):             0.1200
                                           P-value                           0.7293
Time periods:                          3   Distribution:                   F(1,229)
Avg Obs:                          116.00
Min Obs:                          116.00
Max Obs:                          116.00

                                 Parameter Estimates
=====================================================================================
                   Parameter  Std. Err.     T-stat    P-value    Lower CI    Upper CI
-------------------------------------------------------------------------------------
partyline_percent    -177.52     512.40    -0.3465     0.7293     -1187.2      832.11
=====================================================================================

F-test for Poolability: 3.0404
P-value: 0.0000
Distribution: F(117,229)

Included effects: Entity, Time
PanelEffectsResults, id: 0x1e205cd6b50

In [44]:
train_predictions = train_model.predict(train_df[exog_vars])

AssertionError: