In [163]:
import csv
import pandas as pd
from pandas import DataFrame
import statsmodels.api as sm
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [164]:
#Bringing Data into the right format wide_to_long

# Loading data
a = "~/Documents/GitHub/CampaignDonations/Output_Data/Disney_Donor_Vote.csv"
df = pd.read_csv(a)

df = df.drop(columns = ["person", "name_x" ,"party_x", "party_y", "Last_name" , "Suffix" , "LastName", "ID_NameParty", "Pure_name" , "FirstName" , "first" , "last", "religion" ,"death" , "birthplace", "deathplace"])
df.head()

,VoteAlong113thRatio,VoteAlong114thRatio,VoteAlong115thRatio,VoteAlong116thRatio,party_short,donations2012,donations2014,donations2016,donations2018,pageid,...,wikititle,name_y,sex,ethnicity,birth,Number_Sessions_Served,Session_113,Session_114,Session_115,Session_116
0,NaN,NaN,NaN,NaN,N,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,0.00,0.666667,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,0.75,0.333333,0.6,1.0,D,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,0.50,NaN,NaN,NaN,D,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,0.00,0.333333,0.4,1.0,D,0.0,0.0,0.0,1000.0,699496.0,...,Earl_Blumenauer,Earl Blumenauer,male,white,1948-08-16,4.0,True,True,True,True

In [165]:
list(df.columns)

['VoteAlong113thRatio',
 'VoteAlong114thRatio',
 'VoteAlong115thRatio',
 'VoteAlong116thRatio',
 'party_short',
 'donations2012',
 'donations2014',
 'donations2016',
 'donations2018',
 'pageid',
 'wikidataid',
 'wikititle',
 'name_y',
 'sex',
 'ethnicity',
 'birth',
 'Number_Sessions_Served',
 'Session_113',
 'Session_114',
 'Session_115',
 'Session_116']

In [166]:
#df["id"] = df.index
#df.head()

In [175]:
df_long = pd.DataFrame(df[["VoteAlong113thRatio", "VoteAlong114thRatio", "VoteAlong115thRatio", "VoteAlong116thRatio"]])
df_long = df_long.fillna(0)
df_long = pd.DataFrame(df_long)
df_long["id"] = df_long.index

df_long = df_long.astype(float)
df_long.head()

,VoteAlong113thRatio,VoteAlong114thRatio,VoteAlong115thRatio,VoteAlong116thRatio,id
0,0.00,0.000000,0.0,0.0,0.0
1,0.00,0.666667,0.0,0.0,1.0
2,0.75,0.333333,0.6,1.0,2.0
3,0.50,0.000000,0.0,0.0,3.0
4,0.00,0.333333,0.4,1.0,4.0

In [176]:
df_long_2 = pd.DataFrame(df_long)
df_long_2 = pd.wide_to_long(df_long,  ["113thRatio", "114thRatio", "115thRatio","116thRatio"] , i="id", j="'VoteAlong'")

In [177]:
df_long_2.head()

Empty DataFrame
Columns: [VoteAlong113thRatio, VoteAlong115thRatio, VoteAlong114thRatio, VoteAlong116thRatio, 113thRatio, 114thRatio, 115thRatio, 116thRatio]
Index: []

In [ ]:

# What do I need:
#Individual Session_t1 VoteAlong ChangeDonation_t2_minus_t1